-- REPARATION : la premiere synchronisation (fichiers upsert 01-09 puis
-- le patch de rattrapage) a cree 1540 lignes EN DOUBLE au lieu de
-- mettre a jour les articles existants. Cause : la colonne
-- article_normalise deja en base garde les espaces (ex: "ACIDE CITRIQUE"),
-- alors que le script de sync generait une cle sans espaces (ex:
-- "ACIDECITRIQUE") - Postgres ne reconnaissait donc jamais l'article
-- existant et en creait un nouveau a chaque fois.
--
-- Ce script repare en gardant TOUJOURS la ligne d'origine (celle qui a
-- l'historique de stock/BC/recette, ou a defaut la plus ancienne),
-- copie les valeurs categorie/unite/gamme/gamme_statistique/stock min-max
-- de la ligne la plus recente (donnees Excel les plus a jour) sur cette
-- ligne d'origine, PUIS supprime les lignes en double. "utilisation"
-- (champ manuel, jamais dans le fichier Excel) n'est jamais touche.
--
-- 3 groupes ont ete exclus car 2 lignes ou plus ont chacune un vrai
-- historique de stock (fusion automatique risquee - a traiter a la main) :
--   - id 110 "BASE BAM 61034 (SWEET SCENT PEACH PARADISE)" (4 refs) vs id 6400 "BASE BAM 61034 (SWEET SCENT PEACH PARADISE)" (1 refs)
--   - id 219 "BASE SAV 41126" (40 refs) vs id 6477 "BASE SAV 41126" (1 refs)
--   - id 222 "BASE SAV 41433" (28 refs) vs id 6479 "BASE SAV 41433" (1 refs)
--
-- A executer DANS L'ORDRE : les fichiers 01 a 0N (update), PUIS le fichier
-- delete en dernier.
--
-- Partie 1 / 7 (update) : 250 articles.

update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 60000, max_stock = 120000 where id = 1;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 35000, max_stock = 70000 where id = 2;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 17500, max_stock = 35000 where id = 3;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 4;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 250, max_stock = 500 where id = 5;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 15000, max_stock = 30000 where id = 6;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1750, max_stock = 3500 where id = 7;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 175, max_stock = 350 where id = 8;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 40000, max_stock = 80000 where id = 9;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'pcs', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 10;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 12;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 13;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1000, max_stock = 2000 where id = 15;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 18;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 19;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 21;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'pcs', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1500, max_stock = 3000 where id = 22;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 24;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 25;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 29;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 31;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 32;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - SWEET APPLE', min_stock = 75, max_stock = 150 where id = 34;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 36;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'PSA JANNA - ROSE', min_stock = 275, max_stock = 550 where id = 39;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'PSA DEEM', min_stock = 275, max_stock = 550 where id = 40;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 2000, max_stock = 4000 where id = 41;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - WATER MELON', min_stock = 75, max_stock = 150 where id = 42;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'PSA DEEM', min_stock = 275, max_stock = 550 where id = 43;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'PSA JANNA - OUD', min_stock = 275, max_stock = 550 where id = 44;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'PSA JANNA - AMBER', min_stock = 275, max_stock = 550 where id = 45;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - COCONUT CRUSH', min_stock = 75, max_stock = 150 where id = 46;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - 1001 NIGHT', min_stock = 50, max_stock = 100 where id = 47;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'PSA DEEM', min_stock = 275, max_stock = 550 where id = 48;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - GODDESS', min_stock = 37.5, max_stock = 75 where id = 49;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - GODDESS', min_stock = 37.5, max_stock = 75 where id = 50;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - GODDESS', min_stock = 37.5, max_stock = 75 where id = 51;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - 1001 NIGHT', min_stock = 50, max_stock = 100 where id = 52;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - GODDESS', min_stock = 37.5, max_stock = 75 where id = 53;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'PSA DEEM', min_stock = 275, max_stock = 550 where id = 54;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'PSA DEEM', min_stock = 275, max_stock = 550 where id = 56;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'PSA JANNA - SANDAL WOOD', min_stock = 275, max_stock = 550 where id = 59;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'PSA JANNA - BAKHOOR', min_stock = 275, max_stock = 550 where id = 60;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - ENCHANTED', min_stock = 50, max_stock = 100 where id = 61;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 62;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'PSA DEEM', min_stock = 275, max_stock = 550 where id = 63;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - 1001 NIGHT', min_stock = 50, max_stock = 100 where id = 64;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'MINI PARFUM - 6TH SCENT - INSIGHT', min_stock = 75, max_stock = 150 where id = 65;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - GODDESS', min_stock = 37.5, max_stock = 75 where id = 66;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - 1001 NIGHT', min_stock = 50, max_stock = 100 where id = 67;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - 1001 NIGHT', min_stock = 50, max_stock = 100 where id = 68;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'MINI PARFUM - 6TH SCENT - INTUITION', min_stock = 75, max_stock = 150 where id = 69;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'MINI PARFUM - 6TH SCENT - DANGER', min_stock = 50, max_stock = 100 where id = 70;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'PSA JANNA - MUSK', min_stock = 275, max_stock = 550 where id = 71;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'MINI PARFUM - 6TH SCENT - ARCANA', min_stock = 75, max_stock = 150 where id = 72;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'MINI PARFUM - 6TH SCENT - INTUITION', min_stock = 75, max_stock = 150 where id = 73;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 74;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 75;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 300, max_stock = 600 where id = 76;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'REAL CARE', gamme_statistique = 'FAMILY', min_stock = 175, max_stock = 350 where id = 78;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 79;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 80;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 81;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - ORIENTAL SCENT', min_stock = 100, max_stock = 200 where id = 82;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - ORIENTAL SCENT', min_stock = 100, max_stock = 200 where id = 83;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - ORIENTAL SCENT', min_stock = 100, max_stock = 200 where id = 84;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - ORIENTAL SCENT', min_stock = 100, max_stock = 200 where id = 85;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - ORIENTAL SCENT', min_stock = 100, max_stock = 200 where id = 86;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 87;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - ENCHANTED', min_stock = 75, max_stock = 150 where id = 88;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'MINI PARFUM - PRETTY - TULIP', min_stock = 50, max_stock = 100 where id = 89;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'MINI PARFUM - PRETTY - LOTUS', min_stock = 50, max_stock = 100 where id = 90;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'MINI PARFUM - PRETTY - DAHLIA', min_stock = 50, max_stock = 100 where id = 91;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'MINI PARFUM - PRETTY - WATER LILY', min_stock = 50, max_stock = 100 where id = 92;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - ORIENTAL SCENT', min_stock = 100, max_stock = 200 where id = 93;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 94;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 95;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 96;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 97;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - ENCHANTED', min_stock = 50, max_stock = 100 where id = 98;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - ENCHANTED', min_stock = 50, max_stock = 100 where id = 99;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'MINI PARFUM - ENCHANTED', min_stock = 50, max_stock = 100 where id = 100;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 150, max_stock = 300 where id = 101;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 75, max_stock = 150 where id = 102;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 104;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 105;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 100, max_stock = 200 where id = 107;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 200, max_stock = 400 where id = 111;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 75, max_stock = 150 where id = 112;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 50, max_stock = 100 where id = 113;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'pcs', gamme = 'POMMADE ET DIVERS', gamme_statistique = 'AMALIA', min_stock = 12.5, max_stock = 25 where id = 114;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM', gamme_statistique = 'TARGET', min_stock = 1500, max_stock = 3000 where id = 117;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 118;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 119;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 120;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 122;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 123;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 124;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 125;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 127;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 128;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 134;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 135;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 139;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'pcs', gamme = 'POMMADE ET DIVERS', gamme_statistique = 'CŒUR DE VASELINE', min_stock = 75, max_stock = 150 where id = 140;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 3500, max_stock = 7000 where id = 141;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'pcs', gamme = 'POMMADE ET DIVERS', gamme_statistique = 'AMALIA', min_stock = 12.5, max_stock = 25 where id = 142;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 145;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 100, max_stock = 200 where id = 146;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 147;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 148;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 149;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 25, max_stock = 50 where id = 151;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'LUXURY', gamme_statistique = 'AVOCADO', min_stock = 300, max_stock = 600 where id = 153;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 250, max_stock = 500 where id = 154;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 500, max_stock = 1000 where id = 155;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - SUMMER STRAW', min_stock = 75, max_stock = 150 where id = 156;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 300, max_stock = 600 where id = 157;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 158;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 160;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 163;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BABY FACE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 164;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'pcs', gamme = 'POMMADE ET DIVERS', gamme_statistique = 'AMALIA', min_stock = 12.5, max_stock = 25 where id = 165;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 166;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - BOUQUET', min_stock = 150, max_stock = 300 where id = 168;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 174;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 175;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 176;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - BOUQUET', min_stock = 150, max_stock = 300 where id = 178;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 1500, max_stock = 3000 where id = 179;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'pcs', gamme = 'POMMADE ET DIVERS', gamme_statistique = 'AMALIA', min_stock = 12.5, max_stock = 25 where id = 180;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 181;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - BOUQUET', min_stock = 150, max_stock = 300 where id = 182;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 500, max_stock = 1000 where id = 183;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 4000, max_stock = 8000 where id = 184;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 250, max_stock = 500 where id = 185;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 187;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 188;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 189;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 190;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 191;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 192;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - BOUQUET', min_stock = 150, max_stock = 300 where id = 193;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 194;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 195;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BODY MIST - NUIT D''ORIENT - AMBER', min_stock = 75, max_stock = 150 where id = 196;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 200;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - BOUQUET', min_stock = 150, max_stock = 300 where id = 201;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BODY MIST - NUIT D''ORIENT - SANDAL WOOD', min_stock = 75, max_stock = 150 where id = 202;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BODY MIST - NUIT D''ORIENT - JASMINE', min_stock = 75, max_stock = 150 where id = 203;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 1500, max_stock = 3000 where id = 204;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 205;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 207;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 209;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'pcs', gamme = 'POMMADE ET DIVERS', gamme_statistique = 'AMALIA', min_stock = 12.5, max_stock = 25 where id = 211;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 213;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - MANGO BLAST', min_stock = 0, max_stock = 0 where id = 215;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 217;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 125, max_stock = 250 where id = 221;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 15000, max_stock = 30000 where id = 226;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 227;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - BOUQUET', min_stock = 150, max_stock = 300 where id = 228;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 230;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BODY MIST - NUIT D''ORIENT - ORIENTAL OUD', min_stock = 75, max_stock = 150 where id = 232;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 200, max_stock = 400 where id = 233;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 234;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BODY MIST - NUIT D''ORIENT - BLACK MUSK', min_stock = 75, max_stock = 150 where id = 235;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 237;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'BASE', gamme_statistique = 'BASE', min_stock = 0, max_stock = 0 where id = 238;
update public.articles_matiere_premiere set categorie = 'BASE', unite = 'kg', gamme = 'PARFUM RODIS', gamme_statistique = 'BODY MIST - NUIT D''ORIENT - WHITE MUSK', min_stock = 75, max_stock = 150 where id = 241;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 242;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 243;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'pcs', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1250, max_stock = 2500 where id = 244;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 245;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 50, max_stock = 100 where id = 246;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 250, max_stock = 500 where id = 247;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 4000, max_stock = 8000 where id = 248;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 250;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 251;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 252;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 254;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 255;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'pcs', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 256;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 258;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 259;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 260;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 261;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 500, max_stock = 1000 where id = 263;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 264;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 12500, max_stock = 25000 where id = 267;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 268;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 269;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 270;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 272;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 274;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 276;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 277;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1250, max_stock = 2500 where id = 278;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 8000, max_stock = 16000 where id = 280;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 250, max_stock = 500 where id = 281;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 500, max_stock = 1000 where id = 282;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 0.5, max_stock = 1 where id = 283;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'kg', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 0.5, max_stock = 1 where id = 284;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'POMMADE ET DIVERS', gamme_statistique = 'ONE FOR ALL', min_stock = 10000, max_stock = 20000 where id = 288;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 5415, max_stock = 10830 where id = 292;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 7500, max_stock = 15000 where id = 293;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 0, max_stock = 0 where id = 294;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'kg', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 0.5, max_stock = 1 where id = 296;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 0.5, max_stock = 1 where id = 298;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 15000, max_stock = 30000 where id = 299;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 0, max_stock = 0 where id = 300;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 0, max_stock = 0 where id = 301;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'kg', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 0.5, max_stock = 1 where id = 303;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'kg', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 0.5, max_stock = 1 where id = 304;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'LUXURY', gamme_statistique = 'AVOCADO', min_stock = 0, max_stock = 0 where id = 305;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 635, max_stock = 1270 where id = 306;
update public.articles_matiere_premiere set categorie = 'Col_cosm', unite = 'Grs', gamme = 'COLORANT COS.', gamme_statistique = 'COLORANT COS.', min_stock = 3500, max_stock = 7000 where id = 307;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 12000, max_stock = 24000 where id = 309;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 310;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 250, max_stock = 500 where id = 311;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 312;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 313;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 314;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 315;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 316;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 317;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 318;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 319;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 9000, max_stock = 18000 where id = 320;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 20000, max_stock = 40000 where id = 321;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 300, max_stock = 600 where id = 322;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 323;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 324;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 325;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 326;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 327;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 328;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 330;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 331;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 4000, max_stock = 8000 where id = 332;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'pcs', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 333;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 4000, max_stock = 8000 where id = 334;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 335;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 336;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 337;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1500, max_stock = 3000 where id = 338;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 2000, max_stock = 4000 where id = 339;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 750, max_stock = 1500 where id = 340;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 341;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 343;
