-- REPARATION : la premiere synchronisation (fichiers upsert 01-09 puis
-- le patch de rattrapage) a cree 1540 lignes EN DOUBLE au lieu de
-- mettre a jour les articles existants. Cause : la colonne
-- article_normalise deja en base garde les espaces (ex: "ACIDE CITRIQUE"),
-- alors que le script de sync generait une cle sans espaces (ex:
-- "ACIDECITRIQUE") - Postgres ne reconnaissait donc jamais l'article
-- existant et en creait un nouveau a chaque fois.
--
-- Ce script repare en gardant TOUJOURS la ligne d'origine (celle qui a
-- l'historique de stock/BC/recette, ou a defaut la plus ancienne),
-- copie les valeurs categorie/unite/gamme/gamme_statistique/stock min-max
-- de la ligne la plus recente (donnees Excel les plus a jour) sur cette
-- ligne d'origine, PUIS supprime les lignes en double. "utilisation"
-- (champ manuel, jamais dans le fichier Excel) n'est jamais touche.
--
-- 3 groupes ont ete exclus car 2 lignes ou plus ont chacune un vrai
-- historique de stock (fusion automatique risquee - a traiter a la main) :
--   - id 110 "BASE BAM 61034 (SWEET SCENT PEACH PARADISE)" (4 refs) vs id 6400 "BASE BAM 61034 (SWEET SCENT PEACH PARADISE)" (1 refs)
--   - id 219 "BASE SAV 41126" (40 refs) vs id 6477 "BASE SAV 41126" (1 refs)
--   - id 222 "BASE SAV 41433" (28 refs) vs id 6479 "BASE SAV 41433" (1 refs)
--
-- A executer DANS L'ORDRE : les fichiers 01 a 0N (update), PUIS le fichier
-- delete en dernier.
--
-- Partie 2 / 7 (update) : 250 articles.

update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 344;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'pcs', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 345;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 346;
update public.articles_matiere_premiere set categorie = 'DETERGENT', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 347;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 348;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 349;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 350;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 351;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1500, max_stock = 3000 where id = 352;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 353;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1000, max_stock = 2000 where id = 354;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 200000, max_stock = 400000 where id = 355;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 356;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 357;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'pcs', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 360;
update public.articles_matiere_premiere set categorie = 'DETERGENT', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 361;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 362;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 45000, max_stock = 90000 where id = 363;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 12500, max_stock = 25000 where id = 364;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 365;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 175000, max_stock = 350000 where id = 366;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 368;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 369;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 370;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 371;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1750, max_stock = 3500 where id = 372;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 30000, max_stock = 60000 where id = 373;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 4500, max_stock = 9000 where id = 374;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 376;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 100000, max_stock = 200000 where id = 377;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 378;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 381;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 382;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 384;
update public.articles_matiere_premiere set categorie = 'DETERGENT', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 385;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 386;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 387;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 388;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 391;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 393;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 2000, max_stock = 4000 where id = 394;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 2000, max_stock = 4000 where id = 395;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 11000, max_stock = 22000 where id = 396;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 397;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'pcs', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 398;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 2000, max_stock = 4000 where id = 399;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 401;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 402;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 403;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 404;
update public.articles_matiere_premiere set categorie = 'DETERGENT', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 406;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 5000, max_stock = 10000 where id = 407;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 408;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 409;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 411;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 412;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 413;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 414;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 415;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 416;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 417;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 418;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 419;
update public.articles_matiere_premiere set categorie = 'DETERGENT', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 420;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 95000, max_stock = 190000 where id = 421;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 422;
update public.articles_matiere_premiere set categorie = 'DETERGENT', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 423;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 424;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 30000, max_stock = 60000 where id = 425;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 426;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 427;
update public.articles_matiere_premiere set categorie = 'DETERGENT', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 428;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 429;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 430;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 431;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 432;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 12500, max_stock = 25000 where id = 434;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 250, max_stock = 500 where id = 435;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 436;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 438;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 439;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 440;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 1250, max_stock = 2500 where id = 441;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 442;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 443;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 444;
update public.articles_matiere_premiere set categorie = 'mp cosm', unite = 'kg', gamme = 'MP COSM', gamme_statistique = 'MP COSM', min_stock = 0, max_stock = 0 where id = 445;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 90000, max_stock = 180000 where id = 446;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'VIT FEE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 450;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'VIT FEE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 451;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'ANGE BB', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 452;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'ANGE BB', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 453;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BODY SPLASH', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 454;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BODY SPLASH', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 455;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BODY SPLASH', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 456;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BODY SPLASH', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 457;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'LAVE VITRE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 458;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BABY FACE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 471;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BABY FACE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 472;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BABY FACE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 473;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 96000, max_stock = 192000 where id = 474;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 0, max_stock = 0 where id = 475;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 48000, max_stock = 96000 where id = 476;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 24000, max_stock = 48000 where id = 477;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 0, max_stock = 0 where id = 478;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 12000, max_stock = 24000 where id = 479;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 18000, max_stock = 36000 where id = 480;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 9000, max_stock = 18000 where id = 481;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 482;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 483;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 484;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 24000, max_stock = 48000 where id = 485;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 12000, max_stock = 24000 where id = 486;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 48000, max_stock = 96000 where id = 487;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 24000, max_stock = 48000 where id = 488;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 96000, max_stock = 192000 where id = 489;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 48000, max_stock = 96000 where id = 490;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 18000, max_stock = 36000 where id = 499;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 12000, max_stock = 24000 where id = 500;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 6000, max_stock = 12000 where id = 501;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 3000, max_stock = 6000 where id = 502;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 513;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 514;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 515;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 516;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 72000, max_stock = 144000 where id = 517;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 36000, max_stock = 72000 where id = 518;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 108000, max_stock = 216000 where id = 519;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 63000, max_stock = 126000 where id = 520;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 192000, max_stock = 384000 where id = 521;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 0, max_stock = 0 where id = 522;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 192000, max_stock = 384000 where id = 523;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 0, max_stock = 0 where id = 524;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 36000, max_stock = 72000 where id = 525;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 18000, max_stock = 36000 where id = 526;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 12000, max_stock = 24000 where id = 527;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 18000, max_stock = 36000 where id = 528;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 12000, max_stock = 24000 where id = 529;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 6000, max_stock = 12000 where id = 530;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY', min_stock = 18000, max_stock = 36000 where id = 531;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY', min_stock = 12000, max_stock = 24000 where id = 532;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY', min_stock = 6000, max_stock = 12000 where id = 533;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'MEN', min_stock = 18000, max_stock = 36000 where id = 534;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'MEN', min_stock = 12000, max_stock = 24000 where id = 535;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'MEN', min_stock = 6000, max_stock = 12000 where id = 536;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 537;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 2880000, max_stock = 5760000 where id = 547;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 630000, max_stock = 1260000 where id = 548;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 540000, max_stock = 1080000 where id = 553;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 270000, max_stock = 540000 where id = 554;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 9000, max_stock = 18000 where id = 555;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 36000, max_stock = 72000 where id = 556;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 108000, max_stock = 216000 where id = 557;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 540000, max_stock = 1080000 where id = 558;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 72000, max_stock = 144000 where id = 559;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 108000, max_stock = 216000 where id = 560;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 72000, max_stock = 144000 where id = 561;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 540000, max_stock = 1080000 where id = 564;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 565;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 566;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 72000, max_stock = 144000 where id = 573;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 48000, max_stock = 96000 where id = 574;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 18000, max_stock = 36000 where id = 579;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 6000, max_stock = 12000 where id = 580;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 24000, max_stock = 48000 where id = 581;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 48000, max_stock = 96000 where id = 582;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 72000, max_stock = 144000 where id = 583;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 12000, max_stock = 24000 where id = 586;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 590;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 48000, max_stock = 96000 where id = 591;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 12000, max_stock = 24000 where id = 592;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 12000, max_stock = 24000 where id = 593;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY', min_stock = 12000, max_stock = 24000 where id = 594;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'MEN', min_stock = 12000, max_stock = 24000 where id = 595;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 596;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'VIT FEE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 599;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 480000, max_stock = 960000 where id = 600;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 270000, max_stock = 540000 where id = 613;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 120000, max_stock = 240000 where id = 614;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 27000, max_stock = 54000 where id = 615;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 24000, max_stock = 48000 where id = 616;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 48000, max_stock = 96000 where id = 617;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 54000, max_stock = 108000 where id = 618;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 24000, max_stock = 48000 where id = 619;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 620;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 621;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 622;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 36000, max_stock = 72000 where id = 623;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 24000, max_stock = 48000 where id = 624;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 60000, max_stock = 120000 where id = 625;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 30000, max_stock = 60000 where id = 626;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 324000, max_stock = 648000 where id = 627;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 180000, max_stock = 360000 where id = 628;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 18000, max_stock = 36000 where id = 637;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 36000, max_stock = 72000 where id = 638;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 30000, max_stock = 60000 where id = 639;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 9000, max_stock = 18000 where id = 640;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 651;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 652;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 653;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 654;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 144000, max_stock = 288000 where id = 655;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 72000, max_stock = 144000 where id = 656;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 720000, max_stock = 1440000 where id = 663;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 540000, max_stock = 1080000 where id = 664;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 240000, max_stock = 480000 where id = 665;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 600000, max_stock = 1200000 where id = 666;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 720000, max_stock = 1440000 where id = 667;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 0, max_stock = 0 where id = 668;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 144000, max_stock = 288000 where id = 669;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 108000, max_stock = 216000 where id = 670;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 84000, max_stock = 168000 where id = 671;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 48000, max_stock = 96000 where id = 672;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 24000, max_stock = 48000 where id = 673;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 6000, max_stock = 12000 where id = 674;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY', min_stock = 24000, max_stock = 48000 where id = 675;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY', min_stock = 48000, max_stock = 96000 where id = 676;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY', min_stock = 12000, max_stock = 24000 where id = 677;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'MEN', min_stock = 48000, max_stock = 96000 where id = 678;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'MEN', min_stock = 24000, max_stock = 48000 where id = 679;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'MEN', min_stock = 6000, max_stock = 12000 where id = 680;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 682;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'VIT FEE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 689;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 2400000, max_stock = 4800000 where id = 690;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 1620000, max_stock = 3240000 where id = 691;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 720000, max_stock = 1440000 where id = 692;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 693;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BABY FACE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 694;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BABY FACE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 695;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'BABY FACE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 696;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 54000, max_stock = 108000 where id = 697;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 698;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 24000, max_stock = 48000 where id = 715;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 18000, max_stock = 36000 where id = 716;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 12000, max_stock = 24000 where id = 717;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 30000, max_stock = 60000 where id = 718;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 6000, max_stock = 12000 where id = 719;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 12000, max_stock = 24000 where id = 725;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 9000, max_stock = 18000 where id = 726;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 6000, max_stock = 12000 where id = 727;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 30000, max_stock = 60000 where id = 736;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 18000, max_stock = 36000 where id = 737;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 120000, max_stock = 240000 where id = 738;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MY FAMILY CARE', gamme_statistique = 'CITRON', min_stock = 6000, max_stock = 12000 where id = 739;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 744;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 745;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 746;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'NEOVA', gamme_statistique = 'SLEEVE', min_stock = 0, max_stock = 0 where id = 747;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 36000, max_stock = 72000 where id = 748;
update public.articles_matiere_premiere set categorie = 'SLEEVE', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'BABY', min_stock = 24000, max_stock = 48000 where id = 749;
