-- REPARATION : la premiere synchronisation (fichiers upsert 01-09 puis
-- le patch de rattrapage) a cree 1540 lignes EN DOUBLE au lieu de
-- mettre a jour les articles existants. Cause : la colonne
-- article_normalise deja en base garde les espaces (ex: "ACIDE CITRIQUE"),
-- alors que le script de sync generait une cle sans espaces (ex:
-- "ACIDECITRIQUE") - Postgres ne reconnaissait donc jamais l'article
-- existant et en creait un nouveau a chaque fois.
--
-- Ce script repare en gardant TOUJOURS la ligne d'origine (celle qui a
-- l'historique de stock/BC/recette, ou a defaut la plus ancienne),
-- copie les valeurs categorie/unite/gamme/gamme_statistique/stock min-max
-- de la ligne la plus recente (donnees Excel les plus a jour) sur cette
-- ligne d'origine, PUIS supprime les lignes en double. "utilisation"
-- (champ manuel, jamais dans le fichier Excel) n'est jamais touche.
--
-- 3 groupes ont ete exclus car 2 lignes ou plus ont chacune un vrai
-- historique de stock (fusion automatique risquee - a traiter a la main) :
--   - id 110 "BASE BAM 61034 (SWEET SCENT PEACH PARADISE)" (4 refs) vs id 6400 "BASE BAM 61034 (SWEET SCENT PEACH PARADISE)" (1 refs)
--   - id 219 "BASE SAV 41126" (40 refs) vs id 6477 "BASE SAV 41126" (1 refs)
--   - id 222 "BASE SAV 41433" (28 refs) vs id 6479 "BASE SAV 41433" (1 refs)
--
-- A executer DANS L'ORDRE : les fichiers 01 a 0N (update), PUIS le fichier
-- delete en dernier.
--
-- Partie 4 / 7 (update) : 250 articles.

update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PINK LADIES', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1134;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PINK LADIES', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1135;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PINK LADIES', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1136;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PINK LADIES', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1137;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'RAPID WHITE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1138;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'RAPID WHITE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1139;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'RAPID WHITE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1141;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1142;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1143;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1144;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1145;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1146;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1147;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1148;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1149;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1150;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'VANETTY', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1151;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'VANETTY', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1152;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'VANETTY', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1153;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'MENTHOLE', min_stock = 25000, max_stock = 50000 where id = 1157;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'MENTHOLE', min_stock = 25000, max_stock = 50000 where id = 1158;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 72000, max_stock = 144000 where id = 1159;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 72000, max_stock = 144000 where id = 1160;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1161;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 24000, max_stock = 48000 where id = 1162;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 24000, max_stock = 48000 where id = 1163;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 90000, max_stock = 180000 where id = 1164;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 30000, max_stock = 60000 where id = 1165;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 6000, max_stock = 12000 where id = 1166;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 24000, max_stock = 48000 where id = 1167;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 36000, max_stock = 72000 where id = 1168;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 48000, max_stock = 96000 where id = 1171;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 12000, max_stock = 24000 where id = 1172;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 36000, max_stock = 72000 where id = 1173;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 216000, max_stock = 432000 where id = 1174;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SHAMPONG ANGIE', gamme_statistique = 'SHAMPONG ANGIE', min_stock = 0, max_stock = 0 where id = 1175;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SHAMPONG ANGIE', gamme_statistique = 'SHAMPONG ANGIE', min_stock = 0, max_stock = 0 where id = 1176;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1179;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1184;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1185;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1186;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1187;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1188;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1189;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1190;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1191;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1192;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1193;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1194;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1195;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1196;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1197;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1198;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1199;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1200;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1201;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1202;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'SOOPURE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1203;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'ANTISEPTIQUE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1212;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'ANTISEPTIQUE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1213;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'ANTISEPTIQUE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1214;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'ANTISEPTIQUE', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1215;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - SUMMER STRAW', min_stock = 24000, max_stock = 48000 where id = 1216;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - COCONUT CRUSH', min_stock = 24000, max_stock = 48000 where id = 1217;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - MANGO BLAST', min_stock = 24000, max_stock = 48000 where id = 1218;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - PEACH PARADISE', min_stock = 24000, max_stock = 48000 where id = 1219;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - SWEET APPLE', min_stock = 24000, max_stock = 48000 where id = 1220;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT - WATER MELON', min_stock = 24000, max_stock = 48000 where id = 1221;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'DR JOHNSON', min_stock = 378000, max_stock = 756000 where id = 1222;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'ETIQUETTE', min_stock = 0, max_stock = 0 where id = 1223;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 120000, max_stock = 240000 where id = 1224;
update public.articles_matiere_premiere set categorie = 'ETIQUETTE', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 54000, max_stock = 108000 where id = 1225;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'DR JOHNSON', min_stock = 0, max_stock = 0 where id = 1227;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'SKIN LIGHT', min_stock = 0, max_stock = 0 where id = 1228;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1229;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1230;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 2000, max_stock = 4000 where id = 1243;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 2000, max_stock = 4000 where id = 1244;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 0, max_stock = 0 where id = 1245;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 500, max_stock = 1000 where id = 1246;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 500, max_stock = 1000 where id = 1247;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 0, max_stock = 0 where id = 1248;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BIO PERFECT', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1249;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 250, max_stock = 500 where id = 1250;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 250, max_stock = 500 where id = 1251;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1252;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1253;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1254;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 500, max_stock = 1000 where id = 1255;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 500, max_stock = 1000 where id = 1256;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1257;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1258;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1259;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'DR JOHNSON', min_stock = 3000, max_stock = 6000 where id = 1260;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 1000, max_stock = 2000 where id = 1261;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 1000, max_stock = 2000 where id = 1262;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 2000, max_stock = 4000 where id = 1263;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 2000, max_stock = 4000 where id = 1264;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1272;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1273;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 750, max_stock = 1500 where id = 1274;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 750, max_stock = 1500 where id = 1275;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 1500, max_stock = 3000 where id = 1280;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 1750, max_stock = 3500 where id = 1281;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 0, max_stock = 0 where id = 1282;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 0, max_stock = 0 where id = 1283;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 1500, max_stock = 3000 where id = 1284;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 1500, max_stock = 3000 where id = 1285;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 4000, max_stock = 8000 where id = 1286;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 500, max_stock = 1000 where id = 1287;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 500, max_stock = 1000 where id = 1288;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 1000, max_stock = 2000 where id = 1289;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 1000, max_stock = 2000 where id = 1290;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 1000, max_stock = 2000 where id = 1291;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'MENTHOLE', min_stock = 750, max_stock = 1500 where id = 1292;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 40000, max_stock = 80000 where id = 1306;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 17500, max_stock = 35000 where id = 1307;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1308;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1309;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BIO PERFECT', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1310;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 500, max_stock = 1000 where id = 1315;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 500, max_stock = 1000 where id = 1316;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 125, max_stock = 250 where id = 1317;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 500, max_stock = 1000 where id = 1318;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 1500, max_stock = 3000 where id = 1319;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 7500, max_stock = 15000 where id = 1320;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 1000, max_stock = 2000 where id = 1321;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 1500, max_stock = 3000 where id = 1322;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 1000, max_stock = 2000 where id = 1323;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 1000, max_stock = 2000 where id = 1324;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 7500, max_stock = 15000 where id = 1327;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ANGE BB', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1329;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB D''AMOUR', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1330;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB D''AMOUR', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1331;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB D''AMOUR', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1332;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1333;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1337;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 0, max_stock = 0 where id = 1338;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 0, max_stock = 0 where id = 1339;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 1500, max_stock = 3000 where id = 1340;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1343;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - BOUQUET', min_stock = 3000, max_stock = 6000 where id = 1344;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - BOUQUET', min_stock = 3000, max_stock = 6000 where id = 1345;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PARFUM RODIS', gamme_statistique = 'BODY MIST - NUIT D''ORIENT', min_stock = 3000, max_stock = 6000 where id = 1346;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - ORIENTAL SCENT', min_stock = 1500, max_stock = 3000 where id = 1347;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PARFUM REALITY', gamme_statistique = 'BODY MIST - ORIENTAL SCENT', min_stock = 3000, max_stock = 6000 where id = 1348;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PARFUM RODIS', gamme_statistique = 'BOBY MIST - SWEET SCENT', min_stock = 3000, max_stock = 6000 where id = 1349;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 3000, max_stock = 6000 where id = 1360;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 1500, max_stock = 3000 where id = 1361;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 125, max_stock = 250 where id = 1362;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 125, max_stock = 250 where id = 1363;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 125, max_stock = 250 where id = 1364;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1365;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 1000, max_stock = 2000 where id = 1366;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 1000, max_stock = 2000 where id = 1367;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 2500, max_stock = 5000 where id = 1368;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 2500, max_stock = 5000 where id = 1369;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 3500, max_stock = 7000 where id = 1370;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 3500, max_stock = 7000 where id = 1371;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 4000, max_stock = 8000 where id = 1372;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 4000, max_stock = 8000 where id = 1373;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 2000, max_stock = 4000 where id = 1374;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 2000, max_stock = 4000 where id = 1375;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 1250, max_stock = 2500 where id = 1378;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 1500, max_stock = 3000 where id = 1379;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 1250, max_stock = 2500 where id = 1380;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 1500, max_stock = 3000 where id = 1381;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 3000, max_stock = 6000 where id = 1386;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 2000, max_stock = 4000 where id = 1387;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 500, max_stock = 1000 where id = 1388;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 1750, max_stock = 3500 where id = 1389;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 1750, max_stock = 3500 where id = 1390;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 4500, max_stock = 9000 where id = 1391;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 0, max_stock = 0 where id = 1392;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 0, max_stock = 0 where id = 1393;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 8000, max_stock = 16000 where id = 1394;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1400;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1401;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 10000, max_stock = 20000 where id = 1402;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 10000, max_stock = 20000 where id = 1403;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 1500, max_stock = 3000 where id = 1404;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'DR JOHNSON', min_stock = 2000, max_stock = 4000 where id = 1405;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'DR JOHNSON', min_stock = 125, max_stock = 250 where id = 1406;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'DR JOHNSON', min_stock = 500, max_stock = 1000 where id = 1407;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1408;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1409;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1410;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'MATRIX', min_stock = 100, max_stock = 200 where id = 1411;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'MATRIX', min_stock = 0, max_stock = 0 where id = 1412;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'MATRIX', min_stock = 0, max_stock = 0 where id = 1413;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1415;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1417;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 1250, max_stock = 2500 where id = 1422;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 250, max_stock = 500 where id = 1423;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1424;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 125, max_stock = 250 where id = 1425;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 500, max_stock = 1000 where id = 1426;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 1000, max_stock = 2000 where id = 1427;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 1500, max_stock = 3000 where id = 1428;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1431;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 1000, max_stock = 2000 where id = 1432;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 750, max_stock = 1500 where id = 1434;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 1000, max_stock = 2000 where id = 1435;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 250, max_stock = 500 where id = 1436;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 750, max_stock = 1500 where id = 1437;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1438;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1441;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 5000, max_stock = 10000 where id = 1442;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'CARTON', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1444;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 7500, max_stock = 15000 where id = 1460;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR', gamme_statistique = 'BB CLEAR', min_stock = 5000, max_stock = 10000 where id = 1461;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 750, max_stock = 1500 where id = 1462;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BB CLEAR VITAMINE-C', gamme_statistique = 'BB CLEAR VITAMINE-C', min_stock = 1000, max_stock = 2000 where id = 1463;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BIO PERFECT', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1464;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'BIO PERFECT', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1465;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 1000, max_stock = 2000 where id = 1466;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 1500, max_stock = 3000 where id = 1467;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCO CLEAR', gamme_statistique = 'COCO CLEAR', min_stock = 1000, max_stock = 2000 where id = 1468;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1469;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1470;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'COCOA SKIN', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1471;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 1000, max_stock = 2000 where id = 1472;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'DERMA TONE', gamme_statistique = 'DERMA TONE', min_stock = 1000, max_stock = 2000 where id = 1473;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 2500, max_stock = 5000 where id = 1474;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'EGYPTIAN BEAUTY', gamme_statistique = 'EGYPTIAN BEAUTY', min_stock = 2500, max_stock = 5000 where id = 1475;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 9000, max_stock = 18000 where id = 1476;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'ELIXIR', gamme_statistique = 'ELIXIR', min_stock = 7500, max_stock = 15000 where id = 1477;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1484;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MAMASSITA', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1485;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 3000, max_stock = 6000 where id = 1486;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'MOROCCO SKIN', gamme_statistique = 'MOROCCO SKIN', min_stock = 3000, max_stock = 6000 where id = 1487;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 15000, max_stock = 30000 where id = 1494;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 15000, max_stock = 30000 where id = 1495;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PERFECT GLOW', gamme_statistique = 'PERFECT GLOW', min_stock = 10000, max_stock = 20000 where id = 1496;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 12500, max_stock = 25000 where id = 1497;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 20000, max_stock = 40000 where id = 1498;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRECIOUS PERFECT', gamme_statistique = 'PRECIOUS PERFECT', min_stock = 6000, max_stock = 12000 where id = 1499;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 3000, max_stock = 6000 where id = 1500;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'PRO-WHITE', gamme_statistique = 'PRO-WHITE', min_stock = 3500, max_stock = 7000 where id = 1501;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 4500, max_stock = 9000 where id = 1502;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 4500, max_stock = 9000 where id = 1503;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'REAL CARE', gamme_statistique = 'FAMILY - BABY - MEN', min_stock = 3000, max_stock = 6000 where id = 1504;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1506;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'VIT FEE', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1513;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'VIT FEE', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1514;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 50000, max_stock = 100000 where id = 1515;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 45000, max_stock = 90000 where id = 1516;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'WHITE SECRET', gamme_statistique = 'WHITE SECRET', min_stock = 30000, max_stock = 60000 where id = 1517;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'Mentholée', gamme_statistique = 'MATRIX', min_stock = 2000, max_stock = 4000 where id = 1518;
update public.articles_matiere_premiere set categorie = 'CARTON', unite = 'pcs', gamme = 'SKIN LIGHT', gamme_statistique = 'CARTON', min_stock = 0, max_stock = 0 where id = 1519;
