// Configuration par Gamme Statistique du rapport riche (copie fidele des
// fichiers "INV <gamme>.xlsx" fournis par l'utilisateur, un par gamme).
// Chaque fichier a ses propres colonnes/titres/couleurs - jamais suppose
// qu'une gamme copie la structure d'une autre (deja vu : MP COSM et ELIXIR
// n'ont ni les memes colonnes, ni les memes couleurs, ni la meme formule de
// consommation).

export type ColumnKind = "static" | "live" | "editable-text" | "editable-number" | "spacer";

// Champs calcules en direct disponibles pour une colonne "live" - toujours
// les memes peu importe la gamme (Gamme/stock/BC/4D/A commander/consos
// viennent des memes tables articles_matiere_premiere/lots_stock_matiere_
// premiere/bons_commande_matiere_premiere pour tout le monde), seul le nom
// de colonne affiche varie par fichier Excel source.
export type LiveField =
  | "gamme"
  | "stock"
  | "enCoursBc"
  | "qteBcEtDate"
  | "enCours4d"
  | "date4d"
  | "aCommander"
  | "conso1Mois"
  | "conso4Mois"
  | "conso9Mois"
  | "conso12Mois";

export type ColumnDescriptor = {
  key: string;
  label: string;
  kind: ColumnKind;
  liveField?: LiveField;
};

export type LegendEntry = { text: string; bg: string; textColor?: string; bold?: boolean };

export type CategorieStyle = { bg: string; text: string };

export type GammeConfig = {
  // Cle dans donnees[...] qui porte le besoin/stat sur laquelle A COMMANDER
  // et les colonnes conso se basent - le nom exact de cette colonne dans le
  // fichier Excel source varie par gamme (espace ou non, etc.).
  statistiqueKey: string;
  // "rolling12mois" = Conso reelle 12 mois calculee depuis les vraies
  // sorties de stock des 12 derniers mois glissants (MP COSM). "excel6mois"
  // = conso 1 mois = statistiqueKey/6, conso 4 mois = conso1mois*4 (ELIXIR,
  // formule trouvee telle quelle dans le fichier Excel source).
  consoFormula: "rolling12mois" | "excel6mois";
  columns: ColumnDescriptor[];
  // Couleur de fond manuelle sur la cellule DESIGNATION (hex fichier Excel
  // source -> hex CSS), copiee telle quelle depuis l'import, jamais une
  // formule.
  designationCouleurBg: Record<string, string>;
  // Reprend les couleurs de mise en forme conditionnelle trouvees dans le
  // fichier Excel source (conditionalFormatting XML) pour stock bas et
  // A COMMANDER negatif - varient par gamme.
  stockBasBg: string;
  stockBasText: string;
  // Multiplicateur du seuil stock bas (stock < conso1Mois * multiplicateur).
  // La quasi-totalite des fichiers sources utilisent "< 3 mois de conso"
  // (valeur par defaut ci-dessous si absent), mais REAL CARE utilise "< 1
  // mois" - confirme par la formule XML brute du fichier source, jamais a
  // uniformiser sur 3 par erreur.
  stockBasMultiplier?: number;
  redText: string;
  // A COMMANDER negatif en gras en plus de rouge (WHITE SECRET seulement,
  // confirme par styles.xml) - absent/false partout ailleurs.
  redTextBold?: boolean;
  // Regle "DESIGNATION en rouge si stock > conso reelle 12 mois" - propre a
  // MP COSM (son fichier source a cette regle et cette colonne ; ELIXIR
  // n'a ni l'un ni l'autre, donc absent/false pour lui).
  highlightStockOverConso12Mois?: boolean;
  // Legende de rotation sur la cellule ORDRE (seulement les gammes qui ont
  // ce systeme dans leur fichier source, ex: MP COSM). Absent = pas de
  // legende de rotation pour cette gamme.
  categorieStyles?: Record<string, CategorieStyle>;
  // Bloc "Notes" en bas de page, copie fidele du fichier Excel source.
  notesLegend: LegendEntry[];
};

export const GAMME_CONFIGS: Record<string, GammeConfig> = {
  "MP COSM": {
    statistiqueKey: "statistique 4D 6 mois",
    consoFormula: "rolling12mois",
    columns: [
      { key: "Gamme", label: "Gamme", kind: "live", liveField: "gamme" },
      { key: "stock", label: "stock", kind: "live", liveField: "stock" },
      { key: "en cours d'achat BC", label: "en cours d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "Qte BC et Date", label: "Qte BC et Date", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      {
        key: "date le livraison prevu ds 4d",
        label: "date le livraison prevu ds 4d",
        kind: "live",
        liveField: "date4d",
      },
      { key: "avis", label: "avis", kind: "editable-text" },
      { key: "statistique 4D 6 mois", label: "statistique 4D 6 mois", kind: "editable-number" },
      { key: "Statistique 6mois calculé", label: "Statistique 6mois calculé", kind: "static" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "__SPACER__", label: "", kind: "spacer" },
      { key: "tonnage 1 tc", label: "tonnage 1 tc", kind: "editable-number" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "Conso reelle 12mois", label: "Conso reelle 12mois", kind: "live", liveField: "conso12Mois" },
      { key: "conso 9Mois", label: "conso 9Mois", kind: "live", liveField: "conso9Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050", FFFF00: "#FFFF00" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    highlightStockOverConso12Mois: true,
    categorieStyles: {
      "FORTE ROTATION": { bg: "#C55A11", text: "#ffffff" },
      "MOYENNE ROTATION": { bg: "#ffffff", text: "#0f172a" },
      DORMANT: { bg: "#BDD7EE", text: "#0f172a" },
      "NEW PROJECT": { bg: "#E2F0D9", text: "#0f172a" },
    },
    notesLegend: [
      { text: "Stock inférieur à 3 mois de conso", bg: "#FFC7CE", textColor: "#C00000", bold: true },
      { text: "Urgent mettre pression sur rimex  STOCK INFERIEUR A CONSO 4 MOIS", bg: "#FFFF00", bold: true },
      {
        text: "Urgent : verifier la date sur le dossier STOCK INFERIEUR A CONSO 4 MOIS/ CHARBEL",
        bg: "#00B050",
        bold: true,
      },
      { text: "stock dormant", bg: "#BDD7EE", bold: true },
      { text: "article important", bg: "#C55A11", bold: true },
      { text: "Stat 6 mois à mettre (nouveaux produits)", bg: "#FFC000" },
      { text: "BC ayant dépassé 3mois sans retour", bg: "#FF5050" },
      { text: "STAT A METTRE A JOUR", bg: "#FFC000", textColor: "#C00000", bold: true },
      { text: "A FAIRE OBLIGATOIREMENT L'INVENTAIRE TOURNANT CHAQ MOIS", bg: "#00B0F0", bold: true },
      { text: "E.T.D : Estimated Time of Departure (Heure estimée de départ)", bg: "transparent" },
    ],
  },
  ELIXIR: {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso 1 mois", label: "conso 1 mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4 mois", label: "conso 4 mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050", FFFF00: "#FFFF00" },
    stockBasBg: "#E6B9B8",
    stockBasText: "#5c2b2a",
    redText: "#FF0000",
    notesLegend: [
      { text: "Note: urgent: vérifier la date sur le dossier", bg: "#00B050", bold: true },
      { text: "urgent : mettre la pression sur le fournisseur", bg: "#FFFF00", bold: true },
      { text: "NP = Néo Parfum", bg: "transparent" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8", bold: true },
      { text: "commande du moi passé non faite", bg: "#FDEADA" },
      { text: "BC ayant dépassé 3mois sans retour", bg: "#FF0000", bold: true },
      { text: "STAT à METTRE A JOUR", bg: "#FAC090", bold: true },
    ],
  },
  "BB CLEAR": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso 1 mois", label: "conso 1 mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4 mois", label: "conso 4 mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050", FFFF00: "#FFFF00" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    notesLegend: [
      { text: "urgent: vérifier la date sur le dossier", bg: "#00B050" },
      { text: "urgent : mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8" },
      { text: "NP = NEO PARFUMS", bg: "transparent" },
      { text: "STAT A METTRE A JOUR", bg: "#FAC090" },
    ],
  },
  "COLORANT PLASTIQUE": {
    statistiqueKey: "statistique 4D",
    consoFormula: "excel6mois",
    columns: [
      { key: "FAMILLE", label: "FAMILLE", kind: "static" },
      { key: "fournisseur", label: "fournisseur", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cours d'achat BC", label: "en cours d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "conso physique 6mois/2025", label: "conso physique 6mois/2025", kind: "static" },
      { key: "statistique 4D", label: "statistique 4D", kind: "editable-number" },
      { key: "statistique 6mois calculé", label: "statistique 6mois calculé", kind: "static" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "utilisation", label: "utilisation", kind: "static" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso physique moyenne 3 mois", label: "conso physique moyenne 3 mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso réelle 12mois", label: "conso réelle 12mois", kind: "live", liveField: "conso12Mois" },
    ],
    designationCouleurBg: {
      "00B050": "#00B050",
      BDD7EE: "#BDD7EE",
      "9DC3E6": "#9DC3E6",
      FFFF00: "#FFFF00",
      A9D18E: "#A9D18E",
      FFC000: "#FFC000",
      C00000: "#C00000",
      FFD966: "#FFD966",
      "00B0F0": "#00B0F0",
    },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    highlightStockOverConso12Mois: true,
    notesLegend: [
      { text: "STOCK DORMANT", bg: "#BDD7EE" },
      { text: "URGENT : VERIFIER LA DATE SUR LE DOSSIER", bg: "#00B050" },
      { text: "Urgent : Mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "stock dormant", bg: "#A9D18E" },
      { text: "Article identique avec deux ref. diff.", bg: "#FFC000" },
      { text: "ARTICLE IMPORTANT", bg: "#C00000", textColor: "#0000FF" },
      { text: "Stat à completer", bg: "#FFD966", textColor: "#0000FF", bold: true },
      { text: "colorant PET", bg: "#00B0F0", textColor: "#0000FF" },
      { text: "Stock supérieur à 1 an de conso      noté en rouge", bg: "transparent", textColor: "#FF0000" },
    ],
  },
  "MOROCCO SKIN": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { FFFF00: "#FFFF00" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    notesLegend: [
      { text: "Urgent: VERIFIER LA DATE SUR LE DOSSIER", bg: "#00B050" },
      { text: "Urgent: Mettre pression sur le fournisseur", bg: "#FFFF00" },
      { text: "NP = NEO PARFUM", bg: "transparent" },
      { text: "RC= ROYAL-CROWN", bg: "transparent" },
      { text: "MD= MAISON D'ESSENCE", bg: "transparent" },
    ],
  },
  "PRECIOUS PERFECT": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "statistique 4D 6mois calculée", label: "statistique 4D 6mois calculée", kind: "static" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050", FFFF00: "#FFFF00", E6B9B8: "#E6B9B8" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    notesLegend: [
      { text: "URGENT : METTRE PRESSION SUR LE FOURNISSEUR", bg: "#FFFF00" },
      { text: "Urgent : Verifier la date sur le dossier", bg: "#00B050", bold: true },
      { text: "Stock inférieur à 3 mmois de consommation", bg: "#E6B9B8" },
      { text: "NP = NEO PARFUMS", bg: "transparent" },
      { text: "PP = POLY PACK", bg: "transparent" },
    ],
  },
  "PERFECT GLOW": {
    statistiqueKey: "statistique 4D 6 mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cours d'achat BC", label: "en cours d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "Détails BC", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6 mois", label: "statistique 4D 6 mois", kind: "editable-number" },
      { key: "statistique 4D 6 mois calculée", label: "statistique 4D 6 mois calculée", kind: "static" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
      { key: "utilisation", label: "utilisation", kind: "static" },
    ],
    designationCouleurBg: { FFFF00: "#FFFF00", "00B050": "#00B050", E6B9B8: "#E6B9B8", FAC090: "#FAC090" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    notesLegend: [
      { text: "URGENT mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "URGENT : VERIFIER LA DATE SUR LE DOSSIER", bg: "#00B050" },
      { text: "ME = MAISON D'ESSENCE", bg: "transparent", bold: true },
      { text: "CP = CREATIONS ET PARFUMS", bg: "transparent", bold: true },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8" },
      { text: "STAT à METTRE A JOUR", bg: "#FAC090" },
    ],
  },
  "PRO-WHITE": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { FFFF00: "#FFFF00" },
    stockBasBg: "#E6B9B8",
    stockBasText: "#953735",
    redText: "#FF0000",
    notesLegend: [
      { text: "URGENT: mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "urgent: vérifier la date sur le dossier", bg: "#00B050" },
      { text: "VERIFICATION", bg: "#FFC000" },
      { text: "NP = NEO PARFUMS", bg: "transparent" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8", textColor: "#C00000" },
      { text: "BC ayant dépassé 3 mois sans retour", bg: "#FF0000" },
      { text: "STAT à METTRE A JOUR", bg: "#FAC090" },
    ],
  },
  "WHITE SECRET": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "DETAILS BC", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "nombre de dossier avec date prèvue", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { FFFF00: "#FFFF00", "00B050": "#00B050" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "URGENT: mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "urgent: vérifier la date sur le dossier", bg: "#00B050" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8", textColor: "#953735" },
      { text: "CPLA= CPL AROMAS", bg: "transparent" },
      { text: "ME = MAISON D'ESSENCE", bg: "transparent" },
      { text: "M = Mane", bg: "transparent" },
      { text: "NP = NEO PARFUMS", bg: "transparent" },
      { text: "PP = POLY PACK", bg: "transparent" },
      { text: "RC = ROYAL CROWN", bg: "transparent" },
    ],
  },
  // Les 8 gammes ci-dessous viennent de fichiers Excel a PLUSIEURS onglets
  // (une sous-famille par onglet) - toutes les lignes sont fusionnees ici
  // dans un seul rapport par gamme, la sous-famille etant conservee dans
  // "categorie" (affichee entre parentheses a cote de la designation, voir
  // rapport-table.tsx) uniquement a titre de regroupement visuel, pas comme
  // systeme de couleur (aucune de ces 8 gammes n'a de vraie colonne
  // rotation type MP COSM).
  PARFUM: {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "remarque", label: "", kind: "editable-text" },
      { key: "conso 1 mois", label: "conso 1 mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050", FFFF00: "#FFFF00" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "URGENT : Mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8" },
      { text: "URGENT, VOIR DATE SUR LE DOSSIER", bg: "#00B050" },
      { text: "STAT à METTRE A JOUR", bg: "#FFC000" },
      { text: "NP=NEO PARFUM", bg: "transparent" },
      { text: "CARB=CARBONNEL SA", bg: "transparent" },
      { text: "ME=MAISON D'ESSENCE", bg: "transparent" },
      { text: "CPL=CPL AROMAS", bg: "transparent" },
    ],
  },
  MATRIX: {
    statistiqueKey: "statistique 4D 6 mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6 mois", label: "statistique 4D 6 mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "remarque", label: "", kind: "editable-text" },
      { key: "conso 1 mois", label: "conso 1 mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050", FFFF00: "#FFFF00" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    notesLegend: [
      { text: "URGENT METTRE PRESSION SUR FOURNISSEUR", bg: "#FFFF00" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#F4B2CB" },
      { text: "URGENT : REGARDER LA DATE SUR LE DOSSIER", bg: "#00B050" },
      { text: "Stat à METTRE A JOUR", bg: "#FFC000" },
      { text: "BC ayant dépassé 3mois sans retour", bg: "#FF0000" },
      { text: "PN = PARFUMS DE NICHE", bg: "transparent" },
      { text: "PP = POLY PACK", bg: "transparent" },
      { text: "ME=MAISON D'ESSENCE", bg: "transparent" },
      { text: "CP=creation et parfums", bg: "transparent" },
      { text: "NP= Neo Parfum", bg: "transparent" },
    ],
  },
  "PARFUM RODIS": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "nombre de dossier avec date prèvue", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "remarque", label: "", kind: "editable-text" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050", FFFF00: "#FFFF00" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "NP = NEO PARFUMS", bg: "transparent" },
      { text: "CPL = CPL AROMAS", bg: "transparent" },
      { text: "STAT a completer", bg: "#FFC000" },
    ],
  },
  "PARFUM REALITY": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "enCoursBc", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "enCours4d", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "nombre de dossier avec date prèvue", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "aCommander", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso4mois", label: "conso 4 mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050", FFC000: "#FFC000", FFFF00: "#FFFF00" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "NP = NEO PARFUMS", bg: "transparent" },
      { text: "CPL = CEPL AROMAS", bg: "transparent" },
      { text: "IB = IBERCHEM", bg: "transparent" },
      { text: "STAT a completer", bg: "#FFC000" },
    ],
  },
  "ABSOLUTE CARE": {
    statistiqueKey: "statistique 4D 6 mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "fournisseur", label: "fournisseur", kind: "static" },
      { key: "stock", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "enCoursBc", label: "en cours d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "enCours4d", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "remarque", label: "", kind: "static" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6 mois", label: "statistique 4D 6 mois", kind: "editable-number" },
      { key: "aCommander", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { EBF1DE: "#EBF1DE", FFFF00: "#FFFF00" },
    stockBasBg: "#E6B9B8",
    stockBasText: "#C00000",
    redText: "#FF0000",
    notesLegend: [
      { text: "URGENT mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "URGENT : VERIFIER LA DATE SUR LE DOSSIER", bg: "#00B050" },
      { text: "ME = MAISON D'ESSENCE", bg: "transparent" },
      { text: "CP = CREATIONS ET PARFUMS", bg: "transparent" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8" },
      { text: "Statistique à mettre à jour", bg: "#FFC000" },
    ],
  },
  "REAL CARE": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "enCoursBc", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "enCours4d", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "nombre de dossier avec date prèvue", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "aCommander", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { EBF1DE: "#EBF1DE", FFFF00: "#FFFF00", "00B050": "#00B050" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    // Seul fichier des 15 ou la regle stock-bas est "< 1 mois de conso" (pas
    // "< 3 mois" comme partout ailleurs) - confirme par la formule XML brute
    // du fichier source (=$N3/=$M3, sans x3).
    stockBasMultiplier: 1,
    redText: "#FF0000",
    notesLegend: [],
  },
  LUXURY: {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "nombre de dossier avec date prèvue", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "colL_unlabeled", label: "", kind: "editable-text" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { FFFF00: "#FFFF00", "00B050": "#00B050", FFC000: "#FFC000", EBF1DE: "#EBF1DE" },
    stockBasBg: "#F5C1C1",
    stockBasText: "#953735",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "NP (NEO PARFUMS)", bg: "transparent" },
      { text: "Urgent: VERIFIER LA DATE SUR LE DOSSIER", bg: "#00B050" },
      { text: "Urgent: Mettre pression sur le fournisseur", bg: "#FFFF00" },
    ],
  },
  "POMMADE ET DIVERS": {
    statistiqueKey: "statistique",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cours bc", label: "en cours bc", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cours 4D", label: "en cours 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique", label: "statistique 4D", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "noteCol", label: "", kind: "editable-text" },
      { key: "year2025", label: "2025", kind: "static" },
      { key: "conso 1 mois", label: "conso 1 mois", kind: "live", liveField: "conso1Mois" },
      { key: "Conso 4mois", label: "Conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050", FFFF00: "#FFFF00" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "Urgent: verifier la date sur le dossier", bg: "#00B050" },
      { text: "Urgent: Mettre pression sur le fournisseur", bg: "#FFFF00" },
      { text: "Stat à Complèter", bg: "#FFC000" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8" },
      { text: "BC ayant dépassé 3mois sans retour", bg: "#FF0000" },
      { text: "PN = PARFUMS DE NICHE", bg: "transparent" },
      { text: "PP = POLY PACK", bg: "transparent" },
      { text: "IB=IBERCHEM", bg: "transparent" },
      { text: "NP=NEO PARFUM", bg: "transparent" },
      { text: "ME=MAISON D'ESSENCE", bg: "transparent" },
      { text: "CP=creation et parfums", bg: "transparent" },
    ],
  },
  "DERMA TONE": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "nombre de dossier avec date prèvue", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "__SPACER__", label: "", kind: "spacer" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050" },
    stockBasBg: "#FF9999",
    stockBasText: "#C00000",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [],
  },
  "COLORANT COSMETIQUE": {
    statistiqueKey: "statistique 4D 6 Mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "stock reel /g", label: "stock reel /g", kind: "live", liveField: "stock" },
      { key: "en cours d'achat BC", label: "en cours d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6 Mois", label: "statistique 4D 6 Mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "UTILISATION", label: "UTILISATION", kind: "static" },
      { key: "conso 1 mois", label: "conso 1 mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4 mois", label: "conso 4 mois", kind: "live", liveField: "conso4Mois" },
      { key: "conso reel 12 mois", label: "conso reel 12 mois", kind: "live", liveField: "conso12Mois" },
    ],
    designationCouleurBg: {},
    stockBasBg: "#FF9999",
    stockBasText: "#C00000",
    // Regle reelle de ce fichier : stock compare directement a "conso 4
    // mois" (= conso1mois*4), pas conso1mois*3 comme la majorite des
    // gammes - confirme par la formule XML brute (C3<$M3), la legende du
    // fichier dit pourtant "3 mois" (divergence signalee, pas corrigee).
    stockBasMultiplier: 4,
    redText: "#FF0000",
    redTextBold: true,
    highlightStockOverConso12Mois: true,
    notesLegend: [
      { text: "Urgent: Mettre pression sur le fournisseur", bg: "#FFFF00" },
      { text: "urgent: vérifier la date sur le dossier", bg: "#00B050" },
      { text: "Stat à completer", bg: "#FFD966" },
      { text: "Stock inferieur à 3 mois de consommation", bg: "#E98F9E" },
    ],
  },
  "MP PLASTIQUE": {
    statistiqueKey: "statistique 4D",
    consoFormula: "excel6mois",
    columns: [
      { key: "fournisseur", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cours d'achat BC", label: "en cours d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "Détails BC", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "Détails Import", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D", label: "statistique 4D", kind: "editable-number" },
      { key: "statistique 6mois calculé", label: "statistique 6mois calculé", kind: "static" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "CONSO 2025", label: "CONSO 2025", kind: "static" },
      { key: "utilisation", label: "", kind: "static" },
      { key: "QUANTITE TC", label: "QUANTITE TC", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "Conso reelle 12mois", label: "Conso reelle 12mois", kind: "live", liveField: "conso12Mois" },
      { key: "col_R_unlabeled", label: "", kind: "static" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { "00B050": "#00B050" },
    stockBasBg: "#DE96A7",
    stockBasText: "#8A042D",
    redText: "#FF0000",
    redTextBold: true,
    highlightStockOverConso12Mois: true,
    notesLegend: [
      { text: "URGENT: VERIFIER LA DATE SUR LE DOSSIER / CHARBEL", bg: "#00B050" },
      { text: "RESINE PET  RELIANCE G5841 M  /  REFERENCE A COMMANDE", bg: "#FFC000" },
      { text: "A FAIRE OBLIGATOIREMENT L INVENTAIRE TOURNANT CHAQ MOIS ", bg: "#00B0F0" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#F8A09E" },
    ],
  },
  "COCO CLEAR": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "a commander", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
      { key: "remarque", label: "", kind: "static" },
    ],
    designationCouleurBg: { FFFF00: "#FFFF00", "00B050": "#00B050" },
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "URGENT : Mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "NP = NEO PARFUMS", bg: "transparent" },
      { text: "Stock infériur à 3 mois de consommation", bg: "#E6B9B8", textColor: "#C00000" },
    ],
  },
  "EGYPTIAN BEAUTY": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "__SPACER__", label: "", kind: "spacer" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
      { key: "remarque", label: "", kind: "static" },
    ],
    designationCouleurBg: {},
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "URGENT: mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "urgent: vérifier la date sur le dossier", bg: "#00B050" },
      { text: "stat à completer", bg: "#FFC000" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8", textColor: "#C00000" },
    ],
  },
  "BB CLEAR VIT C": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "remarque", label: "", kind: "editable-text" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: {},
    stockBasBg: "#E6B9B8",
    stockBasText: "#953735",
    // Regle gagnante de ce fichier compare le stock a "conso 4 mois" (donc
    // multiplicateur effectif 4), confirme par la formule XML brute - la
    // legende dit "3 mois" mais la vraie regle qui l'emporte utilise 4.
    stockBasMultiplier: 4,
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "Stock inferieur à 3mois de conso", bg: "#E6B9B8", textColor: "#953735" },
      { text: "Urgent: VERIFIER LA DATE SUR LE DOSSIER", bg: "#00B050" },
      { text: "Urgent: Mettre pression sur le fournisseur", bg: "#FFFF00" },
      { text: "NP = NEO PARFUM", bg: "transparent" },
    ],
  },
  "ANTI-MOSQUITO": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "dz", label: "dz", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "a commander", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: {},
    stockBasBg: "#FFC7CE",
    stockBasText: "#9C0006",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "Urgent mettre pression sur FOURNISSEUR  STOCK INFERIEUR A CONSO 4 MOIS", bg: "#FFFF00", bold: true },
      { text: "Urgent : verifier la date sur le dossier STOCK INFERIEUR A CONSO 4 MOIS/ CHARBEL", bg: "#00B050", bold: true },
      { text: "Stat 6 mois à mettre (nouveaux produits)", bg: "#FFC000" },
      { text: "Stock infériur à 3 mois de consommation", bg: "#E6B9B8", textColor: "#C00000" },
    ],
  },
  "TONE THERAPY": {
    statistiqueKey: "statistique 4D 6mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cour d'achat BC", label: "en cour d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "nombre de dossier avec date prèvue", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6mois", label: "statistique 4D 6mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "2025", label: "2025", kind: "static" },
      { key: "remarque", label: "", kind: "editable-text" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso 4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
    ],
    designationCouleurBg: { E2F0D9: "#E2F0D9", FFFF00: "#FFFF00" },
    stockBasBg: "#FEBEF2",
    stockBasText: "#C00000",
    redText: "#FF0000",
    redTextBold: true,
    notesLegend: [
      { text: "Stock inférieur à 3 mois de conso", bg: "#FEBEF2", textColor: "#C00000" },
      { text: "Urgent mettre pression sur rimex  STOCK INFERIEUR A CONSO 4 MOIS", bg: "#FFFF00", bold: true },
      { text: "Urgent : verifier la date sur le dossier STOCK INFERIEUR A CONSO 4 MOIS/ CHARBEL", bg: "#00B050", bold: true },
    ],
  },
  "MY FAMILY CARE": {
    statistiqueKey: "statistique 4D 6 mois",
    consoFormula: "excel6mois",
    columns: [
      { key: "unite", label: "", kind: "static" },
      { key: "stock reel", label: "stock reel", kind: "live", liveField: "stock" },
      { key: "en cours d'achat BC", label: "en cours d'achat BC", kind: "live", liveField: "enCoursBc" },
      { key: "__BC_DETAIL__", label: "", kind: "live", liveField: "qteBcEtDate" },
      { key: "en cour d'achat 4D", label: "en cour d'achat 4D", kind: "live", liveField: "enCours4d" },
      { key: "__4D_DETAIL__", label: "", kind: "live", liveField: "date4d" },
      { key: "avis", label: "avis", kind: "editable-number" },
      { key: "statistique 4D 6 mois", label: "statistique 4D 6 mois", kind: "editable-number" },
      { key: "A COMMANDER", label: "A COMMANDER", kind: "live", liveField: "aCommander" },
      { key: "STAT ALMOND", label: "", kind: "static" },
      { key: "2025", label: "", kind: "static" },
      { key: "conso 1mois", label: "conso 1mois", kind: "live", liveField: "conso1Mois" },
      { key: "conso4mois", label: "conso 4mois", kind: "live", liveField: "conso4Mois" },
      { key: "remarque", label: "", kind: "static" },
    ],
    designationCouleurBg: { EBF1DE: "#EBF1DE" },
    stockBasBg: "#E6B9B8",
    stockBasText: "#C00000",
    redText: "#FF0000",
    notesLegend: [
      { text: "URGENT mettre la pression sur le fournisseur", bg: "#FFFF00" },
      { text: "URGENT : VERIFIER LA DATE SUR LE DOSSIER", bg: "#00B050" },
      { text: "ME = MAISON D'ESSENCE", bg: "transparent" },
      { text: "CP = CREATIONS ET PARFUMS", bg: "transparent" },
      { text: "Stock inférieur à 3 mois de consommation", bg: "#E6B9B8", textColor: "#903C3A" },
      { text: "Statistique à completer", bg: "#FFC000" },
    ],
  },
};
