-- "Nouvelle entree" Lab peut deja contenir plusieurs articles dans un seul
-- Save (formulaire multi-lignes), mais chaque ligne devenait une entree
-- completement separee, sans lien entre elles. Ajoute une table "batch"
-- (1 ligne = 1 Save = 1 "CLAB") pour regrouper les articles enregistres
-- ensemble et retrouver un papier imprimable CLAB1/CLAB2/... avec tous les
-- codes de ce Save.
create table if not exists public.qualite_lab_code_batches (
  id bigint generated by default as identity primary key,
  utilisateur text,
  created_at timestamptz not null default now()
);

alter table public.qualite_lab_code_generations
  add column if not exists batch_id bigint references public.qualite_lab_code_batches(id);

create index if not exists qualite_lab_code_generations_batch_id_idx
  on public.qualite_lab_code_generations (batch_id);

-- Backfill : les entrees creees avant cette table sont regroupees par Save
-- d'origine en supposant que les lignes inserees dans le meme Save
-- partagent exactement le meme created_at (insert multi-lignes en une seule
-- requete = meme horodatage de transaction Postgres).
do $$
declare
  grp record;
  new_batch_id bigint;
begin
  for grp in
    select created_at, min(utilisateur) as utilisateur
    from public.qualite_lab_code_generations
    where batch_id is null
    group by created_at
  loop
    insert into public.qualite_lab_code_batches (utilisateur, created_at)
    values (grp.utilisateur, grp.created_at)
    returning id into new_batch_id;

    update public.qualite_lab_code_generations
    set batch_id = new_batch_id
    where created_at = grp.created_at
      and batch_id is null;
  end loop;
end $$;

alter table public.qualite_lab_code_generations
  alter column batch_id set not null;
