-- Sous-module "Generation de codes" dans Qualite > Lab : garde une entree
-- (article + qt vrac + nb de code + type auto/manuel) que l'utilisateur peut
-- rouvrir plus tard pour generer des codes successifs a partir du dernier
-- code Lab connu de l'article (lab_code_auto/lab_code_manu). Totalement
-- separe de Code par article (Production)/Ravitailleur - meme principe
-- d'independance que le reste du module Lab.
create table if not exists public.qualite_lab_code_generations (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id),
  qt_vrac numeric,
  nb_code integer not null,
  type text not null check (type in ('auto', 'manuel')),
  generated_codes jsonb not null default '[]'::jsonb,
  utilisateur text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists qualite_lab_code_generations_article_id_idx
  on public.qualite_lab_code_generations (article_id);
