-- ============================================================
-- V2 (dev) uniquement - a coller dans le projet V2 > SQL Editor > New query.
--
-- Pendant la copie complete des donnees V1 -> V2, plusieurs tables de V2
-- se sont revelees en retard sur V1 (colonnes ajoutees a V1 au fil des
-- mois mais jamais synchronisees vers V2), et 2 tables manquent
-- completement. Ce fichier comble tout ca, plus autorise l'insertion
-- explicite d'id (necessaire pour copier les lignes de V1 en gardant les
-- memes id, sinon toutes les relations entre tables casseraient).
-- ============================================================

-- Colonnes manquantes sur programme_lignes
alter table public.programme_lignes
  add column if not exists numero_lot_detail jsonb,
  add column if not exists confirme_production boolean not null default true,
  add column if not exists remarque text;

-- Colonnes manquantes sur production_rapports
alter table public.production_rapports
  add column if not exists fabrication_arret_absence_air numeric,
  add column if not exists fabrication_arret_absence_vapeur numeric,
  add column if not exists fabrication_arret_attente_aspiration_aqueuse numeric,
  add column if not exists fabrication_arret_attente_cuves_mobiles numeric,
  add column if not exists fabrication_arret_attente_eau_osmosee numeric,
  add column if not exists fabrication_arret_coupure_electrique numeric,
  add column if not exists fabrication_arret_maintenance_plateforme numeric,
  add column if not exists fabrication_arret_manque_cuves_mobiles numeric,
  add column if not exists fabrication_arret_probleme_pompe numeric,
  add column if not exists fabrication_arret_probleme_ph numeric,
  add column if not exists fabrication_arret_probleme_technique numeric,
  add column if not exists date_emballage date,
  add column if not exists code text not null default '';

-- Colonne manquante sur production_carton_entries / production_vrac_entries
-- / production_emballage_entries
alter table public.production_carton_entries add column if not exists code text not null default '';
alter table public.production_vrac_entries add column if not exists code text not null default '';
alter table public.production_emballage_entries add column if not exists code text not null default '';

-- Colonne manquante sur fifo_resultats
alter table public.fifo_resultats add column if not exists preparateur text;

-- Colonne manquante sur programme_dispatcher_history
alter table public.programme_dispatcher_history add column if not exists source_groupe_id bigint;

-- Tables manquantes en entier
create table if not exists public.production_code_termine (
  id bigserial primary key,
  programme_ligne_id bigint not null references public.programme_lignes(id),
  code text not null,
  stage text not null check (stage in ('vrac', 'carton', 'emballage')),
  termine_date timestamptz not null default now(),
  unique (programme_ligne_id, code, stage)
);
create index if not exists production_code_termine_ligne_idx
  on public.production_code_termine (programme_ligne_id);

create table if not exists public.pending_article_code_updates (
  id bigserial primary key,
  groupe_id bigint not null,
  article_id bigint not null references public.articles(id),
  code_manu text,
  code_auto text,
  created_at timestamptz not null default now(),
  unique (groupe_id, article_id)
);
create index if not exists pending_article_code_updates_groupe_id_idx
  on public.pending_article_code_updates (groupe_id);

-- Autorise l'insertion explicite d'id (pour copier V1 en gardant les
-- memes id sur ces 4 tables - "generated always" refuse toute valeur
-- explicite, "generated by default" l'autorise sans rien changer d'autre).
alter table public.machines alter column id set generated by default;
alter table public.machine_produits alter column id set generated by default;
alter table public.recettes_pf alter column id set generated by default;
alter table public.programmes alter column id set generated by default;
