-- Import du rapport TONE THERAPY (onboarding multi-gammes Statistique MP, lot 2).
-- 84 articles. Fichier source multi-onglets : ordre renumerote sequentiellement (1..84), la sous-famille d'origine est gardee dans la colonne categorie.
-- A executer dans Supabase SQL Editor (la table existe deja, creee pour MP COSM).

insert into public.rapport_gamme_statistique_mp
  (gamme_statistique, ordre, designation, categorie, donnees)
values
  ('TONE THERAPY', 1, 'BASE COLOR COFFEE 336466', 'INTENSE', '{"2025":41,"unite":"LUZI","avis":null,"statistique 4D 6mois":200,"remarque":null}'::jsonb),
  ('TONE THERAPY', 2, 'BASE GEL TT INTENSE 336466-B', 'INTENSE', '{"2025":102,"unite":"LUZI","avis":null,"statistique 4D 6mois":100,"remarque":null}'::jsonb),
  ('TONE THERAPY', 3, 'CARTON CREME TONE THERAPY INT. 150ML', 'INTENSE', '{"2025":40,"unite":"4DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 4, 'CARTON CREME TONE THERAPY INT. 300ML', 'INTENSE', '{"2025":36,"unite":"2DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 5, 'CARTON CREME TONE THERAPY INT. 450ML', 'INTENSE', '{"2025":29,"unite":"1DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 6, 'CARTON DSR TONE THERAPY INT. 25ML', 'INTENSE', '{"2025":113,"unite":"6DZ","avis":null,"statistique 4D 6mois":1000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 7, 'CARTON GEL DOUCHE TONE THERAPY INT. CLARIFIANT 1L', 'INTENSE', '{"2025":330,"unite":"1DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 8, 'CARTON GEL DOUCHE TONE THERAPY INT. CLARIFIANT 500ML', 'INTENSE', '{"2025":200,"unite":"2DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 9, 'CARTON GEL DOUCHE TONE THERAPY INT. EXFOLIANT 1L', 'INTENSE', '{"2025":472,"unite":"1DZ","avis":null,"statistique 4D 6mois":2000,"remarque":"COMMANDE A FAIRE APRES BAT CHARGE EMANUEL","designation_couleur":"FFFF00"}'::jsonb),
  ('TONE THERAPY', 10, 'CARTON GEL DOUCHE TONE THERAPY INT. EXFOLIANT 500ML', 'INTENSE', '{"2025":432,"unite":"2DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"FFFF00"}'::jsonb),
  ('TONE THERAPY', 11, 'CARTON HUILE TONE THERAPY INT. 60ML', 'INTENSE', '{"2025":120,"unite":"4DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 12, 'CARTON LAIT TONE THERAPY INT. 200ML', 'INTENSE', '{"2025":237,"unite":"3DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 13, 'CARTON LAIT TONE THERAPY INT. 300ML', 'INTENSE', '{"2025":239,"unite":"2DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 14, 'CARTON LAIT TONE THERAPY INT. 500ML', 'INTENSE', '{"2025":316,"unite":"1DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 15, 'CARTON SAVON TONE THERAPY INT. 200GR', 'INTENSE', '{"2025":180,"unite":"4DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 16, 'CARTON SERUM TONE THERAPY INT. 30ML', 'INTENSE', '{"2025":148,"unite":"4DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 17, 'ETIQUETTE GEL DOUCHE TONE THERAPY INTENSE CLAR.1L', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 18, 'ETIQUETTE GEL DOUCHE TONE THERAPY INTENSE CLAR.500ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 19, 'ETIQUETTE GEL DOUCHE TONE THERAPY INTENSE EXFL.1L', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 20, 'ETIQUETTE GEL DOUCHE TONE THERAPY INTENSE EXFL.500ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 21, 'ETUIS CREME TONE THERAPY INTENSE 150ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 22, 'ETUIS CREME TONE THERAPY INTENSE 300ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":12000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 23, 'ETUIS CREME TONE THERAPY INTENSE 450ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":6000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 24, 'ETUIS DSR TONE THERAPY INTENSE 25ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 25, 'ETUIS HUILE TONE THERAPY INTENSE. 60ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 26, 'ETUIS LAIT TONE THERAPY INTENSE 200ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 27, 'ETUIS LAIT TONE THERAPY INTENSE 300ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 28, 'ETUIS LAIT TONE THERAPY INTENSE 500ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 29, 'ETUIS SAVON TONE THERAPY INTENSE 200GR', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 30, 'ETUIS SERUM TONE THERAPY INTENSE 30ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 31, 'ETUIS TONE THERAPY INTENSE DSR DISPENSEURS 12*25ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":6000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 32, 'GLASS BOTTLE SERUM TONE THERAPY INTENSE IMP', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 33, 'SLEEVE CREME TONE THERAPY INTENSE 150ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 34, 'SLEEVE CREME TONE THERAPY INTENSE 300ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":12000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 35, 'SLEEVE CREME TONE THERAPY INTENSE 450ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":6000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 36, 'SLEEVE DSR TONE THERAPY INTENSE 25ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 37, 'SLEEVE HUILE TONE THERAPY INTENSE 60ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 38, 'SLEEVE LAIT TONE THERAPY INTENSE 200ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 39, 'SLEEVE LAIT TONE THERAPY INTENSE 300ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 40, 'SLEEVE LAIT TONE THERAPY INTENSE 500ML', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 41, '28/410 SCREW LOTION PUMP SILVER JY8644 // BC-254 275MM', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 42, 'PIPETTE SERUM 20/66 SILVER (ABSL+TT)', 'INTENSE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":240,"remarque":"Absolute care + Tone therapy"}'::jsonb),
  ('TONE THERAPY', 43, 'BASE COLOR CARAMEL 336364', 'ADVANCED', '{"2025":55,"unite":"LUZI","avis":null,"statistique 4D 6mois":400,"remarque":null}'::jsonb),
  ('TONE THERAPY', 44, 'BASE GEL TT ADVANCED 336364-F', 'ADVANCED', '{"2025":130,"unite":"LUZI","avis":null,"statistique 4D 6mois":150,"remarque":null}'::jsonb),
  ('TONE THERAPY', 45, 'CARTON CREME TONE THERAPY ADV. 150ML', 'ADVANCED', '{"2025":59,"unite":"4DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 46, 'CARTON CREME TONE THERAPY ADV. 300ML', 'ADVANCED', '{"2025":52,"unite":"2DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 47, 'CARTON CREME TONE THERAPY ADV. 450ML', 'ADVANCED', '{"2025":34,"unite":"1DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 48, 'CARTON DSR TONE THERAPY ADV. 25ML', 'ADVANCED', '{"2025":129,"unite":"6DZ","avis":null,"statistique 4D 6mois":1000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 49, 'CARTON GEL DOUCHE TONE THERAPY ADV. CLARIFIANT 1L', 'ADVANCED', '{"2025":380,"unite":"1DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 50, 'CARTON GEL DOUCHE TONE THERAPY ADV. CLARIFIANT 500ML', 'ADVANCED', '{"2025":219,"unite":"2DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 51, 'CARTON GEL DOUCHE TONE THERAPY ADV. EXFOLIANT 1L', 'ADVANCED', '{"2025":592,"unite":"1DZ","avis":null,"statistique 4D 6mois":2000,"remarque":"COMMANDE A FAIRE APRES BAT CHARGE EMANUEL","designation_couleur":"FFFF00"}'::jsonb),
  ('TONE THERAPY', 52, 'CARTON GEL DOUCHE TONE THERAPY ADV. EXFOLIANT 500ML', 'ADVANCED', '{"2025":637,"unite":"2DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"FFFF00"}'::jsonb),
  ('TONE THERAPY', 53, 'CARTON HUILE TONE THERAPY ADV. 60ML', 'ADVANCED', '{"2025":136,"unite":"4DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 54, 'CARTON LAIT TONE THERAPY ADV. 200ML', 'ADVANCED', '{"2025":400,"unite":"3DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 55, 'CARTON LAIT TONE THERAPY ADV. 300ML', 'ADVANCED', '{"2025":293,"unite":"2DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 56, 'CARTON LAIT TONE THERAPY ADV. 500ML', 'ADVANCED', '{"2025":345,"unite":"1DZ","avis":null,"statistique 4D 6mois":2000,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 57, 'CARTON SAVON TONE THERAPY ADV. 200GR', 'ADVANCED', '{"2025":211,"unite":"4DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 58, 'CARTON SERUM TONE THERAPY ADV. 30ML', 'ADVANCED', '{"2025":178,"unite":"4DZ","avis":null,"statistique 4D 6mois":500,"remarque":null,"designation_couleur":"E2F0D9"}'::jsonb),
  ('TONE THERAPY', 59, 'ETIQUETTE GEL DOUCHE TONE THERAPY ADVANCED CLAR.1L', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 60, 'ETIQUETTE GEL DOUCHE TONE THERAPY ADVANCED CLAR.500ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 61, 'ETIQUETTE GEL DOUCHE TONE THERAPY ADVANCED EXFL.1L', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 62, 'ETIQUETTE GEL DOUCHE TONE THERAPY ADVANCED EXFL.500ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 63, 'ETUIS CREME TONE THERAPY ADVANCED 150ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 64, 'ETUIS CREME TONE THERAPY ADVANCED 300ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":12000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 65, 'ETUIS CREME TONE THERAPY ADVANCED 450ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":6000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 66, 'ETUIS DSR TONE THERAPY ADVANCED 25ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 67, 'ETUIS HUILE TONE THERAPY ADVANCED. 60ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 68, 'ETUIS LAIT TONE THERAPY ADVANCED 200ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 69, 'ETUIS LAIT TONE THERAPY ADVANCED 300ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 70, 'ETUIS LAIT TONE THERAPY ADVANCED 500ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 71, 'ETUIS SAVON TONE THERAPY ADVANCED 200GR', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 72, 'ETUIS SERUM TONE THERAPY ADVANCED 30ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 73, 'ETUIS TONE THERAPY ADVANCED DSR DISPENSEURS 12*25ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":6000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 74, 'GLASS BOTTEL SERUM TONE THERAPY ADVANCED IMP', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 75, 'SLEEVE CREME TONE THERAPY ADVANCED 150ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 76, 'SLEEVE CREME TONE THERAPY ADVANCED 300ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":12000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 77, 'SLEEVE CREME TONE THERAPY ADVANCED 450ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":6000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 78, 'SLEEVE DSR TONE THERAPY ADVANCED 25ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 79, 'SLEEVE HUILE TONE THERAPY ADVANCED 60ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 80, 'SLEEVE LAIT TONE THERAPY ADVANCED 200ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 81, 'SLEEVE LAIT TONE THERAPY ADVANCED 300ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 82, 'SLEEVE LAIT TONE THERAPY ADVANCED 500ML', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":24000,"remarque":null}'::jsonb),
  ('TONE THERAPY', 83, '28/410 SCREW LOTION PUMP SILVER JY8644 // BC-254 275MM', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":null,"remarque":null}'::jsonb),
  ('TONE THERAPY', 84, 'PIPETTE SERUM 20/66 SILVER (ABSL+TT)', 'ADVANCED', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":null,"remarque":"Absolute care + Tone therapy"}'::jsonb)
on conflict (gamme_statistique, ordre) do update set
  designation = excluded.designation,
  categorie = excluded.categorie,
  donnees = excluded.donnees;
