-- Import du rapport PARFUM RODIS (onboarding multi-gammes Statistique MP).
-- 66 articles. Fichier source multi-onglets : ordre renumerote sequentiellement (1..66), la sous-famille d'origine est gardee dans la colonne categorie.
-- A executer dans Supabase SQL Editor (la table existe deja, creee pour MP COSM).

insert into public.rapport_gamme_statistique_mp
  (gamme_statistique, ordre, designation, categorie, donnees)
values
  ('PARFUM RODIS', 1, 'CARTON GAMME SWEET SCENT 150ML', 'BODY MIST', '{"unite":"4dz","avis":null,"statistique 4D 6mois":6000,"remarque":null}'::jsonb),
  ('PARFUM RODIS', 2, 'BASE BAM 61034 (SWEET SCENT PEACH PARADISE)', 'BODY MIST', '{"unite":"NP","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 3, 'ETIQUETTE SWEET SCENT PEACH PARADISE 150ML', 'BODY MIST', '{"unite":null,"avis":0,"statistique 4D 6mois":48000,"remarque":"150 CTS"}'::jsonb),
  ('PARFUM RODIS', 4, 'BASE ALD 20294 (SWEET SCENT SWEET APPLE)', 'BODY MIST', '{"unite":"NP","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 5, 'ETIQUETTE SWEET SCENT SWEET APPLE 150ML', 'BODY MIST', '{"unite":null,"avis":0,"statistique 4D 6mois":48000,"remarque":"150 CTS"}'::jsonb),
  ('PARFUM RODIS', 6, 'BASE SAV 40394 (SWEET SCENT MANGO BLAST)', 'BODY MIST', '{"unite":"NP","avis":25,"statistique 4D 6mois":150,"remarque":100}'::jsonb),
  ('PARFUM RODIS', 7, 'ETIQUETTE SWEET SCENT MANGO BLAST 150ML', 'BODY MIST', '{"unite":null,"avis":0,"statistique 4D 6mois":48000,"remarque":"150 CTS"}'::jsonb),
  ('PARFUM RODIS', 8, 'BASE ALD 23393 (SWEET SCENT COCONUT CRUSH)', 'BODY MIST', '{"unite":"NP","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 9, 'ETIQUETTE SWEET SCENT COCONUT CRUSH 150ML', 'BODY MIST', '{"unite":null,"avis":0,"statistique 4D 6mois":48000,"remarque":"150 CTS"}'::jsonb),
  ('PARFUM RODIS', 10, 'BASE ALD 22706 (SWEET SCENT WATERMELON)', 'BODY MIST', '{"unite":"NP","avis":50,"statistique 4D 6mois":150,"remarque":86}'::jsonb),
  ('PARFUM RODIS', 11, 'ETIQUETTE SWEET SCENT WONDER MELON 150ML', 'BODY MIST', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":"150 CTS"}'::jsonb),
  ('PARFUM RODIS', 12, 'BASE COS 31387 (SWEET SCENT SUMMER STRAW)', 'BODY MIST', '{"unite":"NP","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 13, 'ETIQUETTE SWEET SCENT BERRY WAVE 150ML', 'BODY MIST', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":"150 CTS"}'::jsonb),
  ('PARFUM RODIS', 14, 'CARTON GAMME NUIT D''ORIENT 150ML', 'BODY MIST', '{"unite":"4dz","avis":0,"statistique 4D 6mois":6000,"remarque":null}'::jsonb),
  ('PARFUM RODIS', 15, 'BASE UNDER YOUR SKIN 343966-A', 'BODY MIST', '{"unite":"LUZI","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 16, 'ETIQUETTE NUIT D''ORIENT BLACK MUSK 150ML', 'BODY MIST', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":"2026  35"}'::jsonb),
  ('PARFUM RODIS', 17, 'BASE RAJA 230286', 'BODY MIST', '{"unite":"LUZI","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 18, 'ETIQUETTE NUIT D''ORIENT JASMINE 150ML', 'BODY MIST', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":"2027  35"}'::jsonb),
  ('PARFUM RODIS', 19, 'BASE ORIENTAL TEMPTATION 233795-C', 'BODY MIST', '{"unite":"LUZI","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 20, 'ETIQUETTE NUIT D''ORIENT AMBER 150ML', 'BODY MIST', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":"2028  35"}'::jsonb),
  ('PARFUM RODIS', 21, 'BASE WHITE MUSK GRENADINE 338699', 'BODY MIST', '{"unite":"LUZI","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 22, 'ETIQUETTE NUIT D''ORIENT WHITE MUSK 150ML', 'BODY MIST', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":"2029  35"}'::jsonb),
  ('PARFUM RODIS', 23, 'BASE QUEEN OF MYSORE 352310-C', 'BODY MIST', '{"unite":"LUZI","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 24, 'ETIQUETTE NUIT D''ORIENT SANDALWOOD 150ML', 'BODY MIST', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":"2030  35"}'::jsonb),
  ('PARFUM RODIS', 25, 'BASE SWEET ESCAPE 233206-B', 'BODY MIST', '{"unite":"LUZI","avis":25,"statistique 4D 6mois":150,"remarque":57}'::jsonb),
  ('PARFUM RODIS', 26, 'ETIQUETTE NUIT D''ORIENT ORIENTAL OUD 150ML', 'BODY MIST', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":"2031  35"}'::jsonb),
  ('PARFUM RODIS', 27, '20/415 MIST SPRAY SHINING GOLD 150ML / 125MM', 'BODY MIST', '{"unite":null,"avis":100000,"statistique 4D 6mois":576000,"remarque":"sweet scent + nuit d''orient"}'::jsonb),
  ('PARFUM RODIS', 28, 'CARTON MINI PARFUMS PRETTY', 'MINI PARFUM', '{"unite":48,"avis":null,"statistique 4D 6mois":5000,"remarque":3000}'::jsonb),
  ('PARFUM RODIS', 29, 'BASE AR 891606 UNFORGETTABLE DAHLIA', 'MINI PARFUM', '{"unite":"CPL","avis":null,"statistique 4D 6mois":100,"remarque":"conso 99kg/ans"}'::jsonb),
  ('PARFUM RODIS', 30, 'ETIQUETTE MINI PARFUM PRETTY DAHLIA 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":500}'::jsonb),
  ('PARFUM RODIS', 31, 'BASE AR 891605 UNFORGETTABLE LOTUS', 'MINI PARFUM', '{"unite":"CPL","avis":null,"statistique 4D 6mois":100,"remarque":"conso 99kg/ans"}'::jsonb),
  ('PARFUM RODIS', 32, 'ETIQUETTE MINI PARFUM PRETTY LOTUS 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":500}'::jsonb),
  ('PARFUM RODIS', 33, 'BASE AR 891603 ENCHANTED CHERRY BLOSSOM', 'MINI PARFUM', '{"unite":"CPL","avis":null,"statistique 4D 6mois":null,"remarque":"conso 136kg/ans"}'::jsonb),
  ('PARFUM RODIS', 34, 'ETIQUETTE MINI PARFUM PRETTY ROSE 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":540}'::jsonb),
  ('PARFUM RODIS', 35, 'BASE AR 891604 UNFORGETTABLE TULIP', 'MINI PARFUM', '{"unite":"CPL","avis":null,"statistique 4D 6mois":100,"remarque":"conso 99kg/ans"}'::jsonb),
  ('PARFUM RODIS', 36, 'ETIQUETTE MINI PARFUM PRETTY TULIP 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":500}'::jsonb),
  ('PARFUM RODIS', 37, 'BASE AR 891607 UNFORGETTABLE WATER LILY', 'MINI PARFUM', '{"unite":"CPL","avis":null,"statistique 4D 6mois":100,"remarque":"conso 99kg/ans"}'::jsonb),
  ('PARFUM RODIS', 38, 'ETIQUETTE MINI PARFUM PRETTY WATER LILY 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":500}'::jsonb),
  ('PARFUM RODIS', 39, 'CARTON MINI PARFUMS 6TH SCENT', 'MINI PARFUM', '{"unite":48,"avis":500,"statistique 4D 6mois":5000,"remarque":4000}'::jsonb),
  ('PARFUM RODIS', 40, 'BASE ALM12771 ARCANA', 'MINI PARFUM', '{"unite":"NP","avis":25,"statistique 4D 6mois":150,"remarque":"conso 152kg/ans"}'::jsonb),
  ('PARFUM RODIS', 41, 'ETIQUETTE MINI PARFUM 6TH SCENT ARCANA 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":815}'::jsonb),
  ('PARFUM RODIS', 42, 'BASE ALM12407 DANGER', 'MINI PARFUM', '{"unite":"NP","avis":null,"statistique 4D 6mois":100,"remarque":"conso 88kg/ans"}'::jsonb),
  ('PARFUM RODIS', 43, 'ETIQUETTE MINI PARFUM 6TH SCENT DANGER 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":705}'::jsonb),
  ('PARFUM RODIS', 44, 'BASE ALM13113 INSIGHT', 'MINI PARFUM', '{"unite":"NP","avis":null,"statistique 4D 6mois":150,"remarque":"conso 134kg/ans"}'::jsonb),
  ('PARFUM RODIS', 45, 'ETIQUETTE MINI PARFUM 6TH SCENT INSIGHT 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":705}'::jsonb),
  ('PARFUM RODIS', 46, 'BASE ALM10726 INTUITION', 'MINI PARFUM', '{"unite":"NP","avis":null,"statistique 4D 6mois":150,"remarque":"conso 134kg/ans"}'::jsonb),
  ('PARFUM RODIS', 47, 'ETIQUETTE MINI PARFUM 6TH SCENT INTUITION 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":709}'::jsonb),
  ('PARFUM RODIS', 48, 'BASE ALM12826 WISDOM', 'MINI PARFUM', '{"unite":"NP","avis":null,"statistique 4D 6mois":150,"remarque":"conso 131kg/ans"}'::jsonb),
  ('PARFUM RODIS', 49, 'ETIQUETTE MINI PARFUM 6TH SCENT WISDOM 60ML (R/V)', 'MINI PARFUM', '{"unite":null,"avis":null,"statistique 4D 6mois":48000,"remarque":705}'::jsonb),
  ('PARFUM RODIS', 50, '20/415 MIST SPRAYER SHINING BLACK & BLACK CAP / 76MM', 'MINI PARFUM', '{"unite":null,"avis":93000,"statistique 4D 6mois":528000,"remarque":500000}'::jsonb),
  ('PARFUM RODIS', 51, 'CARTON ROLL-ON PARFUM JANNA 5ML', 'PSA JANNA', '{"unite":18,"avis":null,"statistique 4D 6mois":6000,"remarque":435}'::jsonb),
  ('PARFUM RODIS', 52, 'BASE ALD23285 JANNA', 'PSA JANNA', '{"unite":"NP","avis":null,"statistique 4D 6mois":550,"remarque":91}'::jsonb),
  ('PARFUM RODIS', 53, 'ETUIS PARFUM ROLL-ON JANNA AMBER 5ML', 'PSA JANNA', '{"unite":null,"avis":null,"statistique 4D 6mois":216000,"remarque":"70CT"}'::jsonb),
  ('PARFUM RODIS', 54, 'BASE ALM12717 JANNA', 'PSA JANNA', '{"unite":"NP","avis":null,"statistique 4D 6mois":550,"remarque":49.45}'::jsonb),
  ('PARFUM RODIS', 55, 'ETUIS PARFUM ROLL-ON JANNA BAKHOOR 5ML', 'PSA JANNA', '{"unite":null,"avis":null,"statistique 4D 6mois":216000,"remarque":"70CT"}'::jsonb),
  ('PARFUM RODIS', 56, 'BASE ALM12473 JANNA', 'PSA JANNA', '{"unite":"NP","avis":null,"statistique 4D 6mois":550,"remarque":58.5}'::jsonb),
  ('PARFUM RODIS', 57, 'ETUIS PARFUM ROLL-ON JANNA MUSK 5ML', 'PSA JANNA', '{"unite":null,"avis":null,"statistique 4D 6mois":216000,"remarque":"70CT"}'::jsonb),
  ('PARFUM RODIS', 58, 'BASE ALD22823 JANNA', 'PSA JANNA', '{"unite":"NP","avis":null,"statistique 4D 6mois":550,"remarque":78.6}'::jsonb),
  ('PARFUM RODIS', 59, 'ETUIS PARFUM ROLL-ON JANNA OUD 5ML', 'PSA JANNA', '{"unite":null,"avis":null,"statistique 4D 6mois":216000,"remarque":"75CT"}'::jsonb),
  ('PARFUM RODIS', 60, 'BASE ALD22109 JANNA', 'PSA JANNA', '{"unite":"NP","avis":null,"statistique 4D 6mois":550,"remarque":53.5}'::jsonb),
  ('PARFUM RODIS', 61, 'ETUIS PARFUM ROLL-ON JANNA ROSE 5ML', 'PSA JANNA', '{"unite":null,"avis":null,"statistique 4D 6mois":216000,"remarque":"75CT"}'::jsonb),
  ('PARFUM RODIS', 62, 'BASE ALM11855 JANNA', 'PSA JANNA', '{"unite":"NP","avis":null,"statistique 4D 6mois":550,"remarque":83.2}'::jsonb),
  ('PARFUM RODIS', 63, 'ETUIS PARFUM ROLL-ON JANNA SANDALWOOD 5ML', 'PSA JANNA', '{"unite":null,"avis":null,"statistique 4D 6mois":216000,"remarque":"75CT"}'::jsonb),
  ('PARFUM RODIS', 64, 'GLASS BOTTEL PARFUM ROLL-ON 5ML JANNA', 'PSA JANNA', '{"unite":null,"avis":null,"statistique 4D 6mois":1296000,"remarque":null}'::jsonb),
  ('PARFUM RODIS', 65, 'PLASTIC ROLL-ON BALLS DEEM & JANA', 'PSA JANNA', '{"unite":null,"avis":null,"statistique 4D 6mois":"voire stat Deem","remarque":null}'::jsonb),
  ('PARFUM RODIS', 66, 'GOLDEN ALUMINIUM 1 RING CAP JANNA', 'PSA JANNA', '{"unite":null,"avis":null,"statistique 4D 6mois":1296000,"remarque":null}'::jsonb)
on conflict (gamme_statistique, ordre) do update set
  designation = excluded.designation,
  categorie = excluded.categorie,
  donnees = excluded.donnees;
