-- Import du rapport LUXURY (onboarding multi-gammes Statistique MP).
-- 51 articles. Fichier source multi-onglets : ordre renumerote sequentiellement (1..51), la sous-famille d'origine est gardee dans la colonne categorie.
-- A executer dans Supabase SQL Editor (la table existe deja, creee pour MP COSM).

insert into public.rapport_gamme_statistique_mp
  (gamme_statistique, ordre, designation, categorie, donnees)
values
  ('LUXURY', 1, 'COLORANT JAUNE AU GRAS W1205 COSM - CI12700', 'Cocoa', '{"2025":1799,"unite":null,"avis":1500,"statistique 4D 6mois":8000,"colL_unlabeled":null,"designation_couleur":"FFFF00"}'::jsonb),
  ('LUXURY', 2, 'COLORANT ORANGE AOR7 / CI 15510', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":null,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 3, 'BASE COS 31112 LUXURY COCOA', 'Cocoa', '{"2025":1800,"unite":"NP","avis":null,"statistique 4D 6mois":2500,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 4, 'CARTON CREME LUXURY COCOA 125ML', 'Cocoa', '{"2025":50,"unite":"12 DZ","avis":null,"statistique 4D 6mois":1000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 5, 'CARTON CREME LUXURY COCOA 250ML', 'Cocoa', '{"2025":650,"unite":"6 DZ","avis":null,"statistique 4D 6mois":2000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 6, 'CARTON CREME LUXURY COCOA 500ML', 'Cocoa', '{"2025":1350,"unite":"3 DZ","avis":0,"statistique 4D 6mois":2500,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 7, 'CARTON GEL DOUCHE LUXURY COCOA 750ML', 'Cocoa', '{"2025":2300,"unite":"2 DZ","avis":12000,"statistique 4D 6mois":14000,"colL_unlabeled":6000}'::jsonb),
  ('LUXURY', 8, 'CARTON GEL DOUCHE LUXURY COCOA 750ML exfoliant', 'Cocoa', '{"2025":2900,"unite":"2 DZ","avis":null,"statistique 4D 6mois":null,"colL_unlabeled":8000}'::jsonb),
  ('LUXURY', 9, 'CARTON HUILE LUXURY COCOA 90ML', 'Cocoa', '{"2025":820,"unite":"6 DZ","avis":null,"statistique 4D 6mois":3000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 10, 'CARTON LAIT LUXURY COCOA 250ML', 'Cocoa', '{"2025":700,"unite":"6 DZ","avis":null,"statistique 4D 6mois":2000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 11, 'CARTON LAIT LUXURY COCOA 400ML', 'Cocoa', '{"2025":2800,"unite":"4 DZ","avis":null,"statistique 4D 6mois":5000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 12, 'CARTON LAIT LUXURY COCOA 750ML', 'Cocoa', '{"2025":4800,"unite":"2 DZ","avis":3000,"statistique 4D 6mois":8000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 13, 'CARTON SAVON LUXURY COCOA 200GR', 'Cocoa', '{"2025":1000,"unite":"4 DZ","avis":2000,"statistique 4D 6mois":2000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 14, 'CARTON SERUM LUXURY COCOA 30ML', 'Cocoa', '{"2025":1400,"unite":"4 DZ","avis":0,"statistique 4D 6mois":2500,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 15, 'ETIQUETTE GEL DOUCHE LUXURY COCOA CLAR. 750ML', 'Cocoa', '{"2025":null,"unite":null,"avis":0,"statistique 4D 6mois":144000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 16, 'ETIQUETTE GEL DOUCHE LUXURY COCOA EXFL. 750ML', 'Cocoa', '{"2025":null,"unite":null,"avis":70000,"statistique 4D 6mois":192000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 17, 'ETIQUETTE SERUM LUXURY COCOA 30ML', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":120000,"colL_unlabeled":null,"designation_couleur":"FFFF00"}'::jsonb),
  ('LUXURY', 18, 'ETUIS SAVON LUXURY COCOA 200GR', 'Cocoa', '{"2025":null,"unite":null,"avis":0,"statistique 4D 6mois":96000,"colL_unlabeled":null,"designation_couleur":"FFFF00"}'::jsonb),
  ('LUXURY', 19, 'ETUIS SERUM LUXURY COCOA 30ML', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":120000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 20, 'SLEEVE CREME LUXURY COCOA 125ML', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":144000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 21, 'SLEEVE CREME LUXURY COCOA 250ML', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":144000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 22, 'SLEEVE CREME LUXURY COCOA 500ML', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":90000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 23, 'SLEEVE HUILE LUXURY COCOA 90ML', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":216000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 24, 'SLEEVE LAIT LUXURY COCOA 250ML', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":144000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 25, 'SLEEVE LAIT LUXURY COCOA 400ML', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":240000,"colL_unlabeled":null,"designation_couleur":"00B050"}'::jsonb),
  ('LUXURY', 26, 'SLEEVE LAIT LUXURY COCOA 750ML', 'Cocoa', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":192000,"colL_unlabeled":null,"designation_couleur":"00B050"}'::jsonb),
  ('LUXURY', 27, 'COLORANT VERT A  EAU LUXURY / VERT A EAU TG', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":null,"colL_unlabeled":null,"designation_couleur":"FFC000"}'::jsonb),
  ('LUXURY', 28, 'BASE COS 31127 LUXURY AVOCAT', 'Aovocado', '{"2025":null,"unite":"NP","avis":null,"statistique 4D 6mois":600,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 29, 'CARTON CREME LUXURY AVOCADO 125ML', 'Aovocado', '{"2025":null,"unite":"12 DZ","avis":null,"statistique 4D 6mois":100,"colL_unlabeled":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 30, 'CARTON CREME LUXURY AVOCADO 250ML', 'Aovocado', '{"2025":null,"unite":"6 DZ","avis":null,"statistique 4D 6mois":200,"colL_unlabeled":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 31, 'CARTON CREME LUXURY AVOCADO 500ML', 'Aovocado', '{"2025":null,"unite":"3 DZ","avis":null,"statistique 4D 6mois":300,"colL_unlabeled":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 32, 'CARTON GEL DOUCHE LUXURY AVOCADO 750ML', 'Aovocado', '{"2025":null,"unite":"2 DZ","avis":0,"statistique 4D 6mois":3000,"colL_unlabeled":"CLARIFIANT  1500","designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 33, 'CARTON GEL DOUCHE LUXURYAVOCADO  750ML exfoliant', 'Aovocado', '{"2025":null,"unite":"2 DZ","avis":null,"statistique 4D 6mois":null,"colL_unlabeled":"EXFOLIANT   1500","designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 34, 'CARTON HUILE LUXURY AVOCADO 90ML', 'Aovocado', '{"2025":null,"unite":"6 DZ","avis":null,"statistique 4D 6mois":200,"colL_unlabeled":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 35, 'CARTON LAIT LUXURY AVOCADO 250ML', 'Aovocado', '{"2025":null,"unite":"6 DZ","avis":null,"statistique 4D 6mois":250,"colL_unlabeled":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 36, 'CARTON LAIT LUXURY AVOCADO 400ML', 'Aovocado', '{"2025":null,"unite":"4 DZ","avis":null,"statistique 4D 6mois":300,"colL_unlabeled":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 37, 'CARTON LAIT LUXURY AVOCADO 750ML', 'Aovocado', '{"2025":null,"unite":"2 DZ","avis":0,"statistique 4D 6mois":3000,"colL_unlabeled":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 38, 'CARTON SAVON LUXURY AVOCADO 200GR', 'Aovocado', '{"2025":null,"unite":"4 DZ","avis":null,"statistique 4D 6mois":200,"colL_unlabeled":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 39, 'CARTON SERUM LUXURY AVOCADO 30ML', 'Aovocado', '{"2025":null,"unite":"4 DZ","avis":null,"statistique 4D 6mois":200,"colL_unlabeled":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('LUXURY', 40, 'ETIQUETTE GEL DOUCHE LUXURY AVOCADO CLAR. 750ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":36000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 41, 'ETIQUETTE GEL DOUCHE LUXURY AVOCADO EXFL.750ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":36000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 42, 'ETIQUETTE SERUM LUXURY AVOCADO 30ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":9600,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 43, 'ETUIS SAVON LUXURY AVOCADO 200GR.', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":9600,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 44, 'ETUIS SERUM LUXURY AVOCADO 30ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":9600,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 45, 'SLEEVE CREME LUXURY AVOCADO 125ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":14400,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 46, 'SLEEVE CREME LUXURY AVOCADO 250ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":14400,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 47, 'SLEEVE CREME LUXURY AVOCADO 500ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":10800,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 48, 'SLEEVE HUILE LUXURY AVOCADO 90ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":14400,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 49, 'SLEEVE LAIT LUXURY AVOCADO 250ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":18000,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 50, 'SLEEVE LAIT LUXURY AVOCADO 400ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":14400,"colL_unlabeled":null}'::jsonb),
  ('LUXURY', 51, 'SLEEVE LAIT LUXURY AVOCADO 750ML', 'Aovocado', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6mois":72000,"colL_unlabeled":null,"designation_couleur":"00B050"}'::jsonb)
on conflict (gamme_statistique, ordre) do update set
  designation = excluded.designation,
  categorie = excluded.categorie,
  donnees = excluded.donnees;
