-- Import du rapport MY FAMILY CARE (onboarding multi-gammes Statistique MP, lot 2).
-- 246 articles. Fichier source multi-onglets : ordre renumerote sequentiellement (1..246), la sous-famille d'origine est gardee dans la colonne categorie.
-- A executer dans Supabase SQL Editor (la table existe deja, creee pour MP COSM).

insert into public.rapport_gamme_statistique_mp
  (gamme_statistique, ordre, designation, categorie, donnees)
values
  ('MY FAMILY CARE', 1, 'BASE SWEET ALMOND 1974392', 'ALMOND', '{"2025":650,"unite":"IBR","avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 2, 'BASE SAV 41565', 'ALMOND', '{"2025":105,"unite":"NP","avis":null,"statistique 4D 6 mois":100,"STAT ALMOND":"sav+GD","remarque":null}'::jsonb),
  ('MY FAMILY CARE', 3, 'BASE ALD 20379', 'ALMOND', '{"2025":200,"unite":"NP","avis":null,"statistique 4D 6 mois":150,"STAT ALMOND":"EDC+TALC","remarque":null}'::jsonb),
  ('MY FAMILY CARE', 4, 'CARTON CREME MY FAMILY CARE 100ML', 'ALMOND', '{"2025":223,"unite":72,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 5, 'CARTON CREME MY FAMILY CARE 200ML', 'ALMOND', '{"2025":370,"unite":48,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 6, 'CARTON CREME MY FAMILY CARE 400ML', 'ALMOND', '{"2025":650,"unite":24,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":1000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 7, 'CARTON CREME MY FAMILY CARE 900ML', 'ALMOND', '{"2025":550,"unite":12,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":1000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 8, 'CARTON EDC MY FAMILY CARE 250ML', 'ALMOND', '{"2025":210,"unite":48,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 9, 'CARTON EDC MY FAMILY CARE 500ML', 'ALMOND', '{"2025":180,"unite":24,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 10, 'CARTON EDC MY FAMILY CARE 750ML', 'ALMOND', '{"2025":180,"unite":12,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 11, 'CARTON GEL DOUCHE MY FAMILY CARE 125ML', 'ALMOND', '{"2025":null,"unite":72,"avis":null,"statistique 4D 6 mois":2500,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 12, 'CARTON GEL DOUCHE MY FAMILY CARE 250ML', 'ALMOND', '{"2025":null,"unite":48,"avis":null,"statistique 4D 6 mois":2500,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 13, 'CARTON GEL DOUCHE MY FAMILY CARE 500ML', 'ALMOND', '{"2025":null,"unite":24,"avis":null,"statistique 4D 6 mois":2500,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 14, 'CARTON GEL DOUCHE MY FAMILY CARE 750ML', 'ALMOND', '{"2025":2200,"unite":12,"avis":null,"statistique 4D 6 mois":8000,"STAT ALMOND":3000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 15, 'CARTON GIFT BOX MY FAMILY CARE', 'ALMOND', '{"2025":400,"unite":"6pcs","avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":0,"remarque":"NE PAS COMANDE CAR PRODUIT A SUPRIME VOIRE MR ROUDA ","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 16, 'CARTON HUILE MY FAMILY CARE 90ML', 'ALMOND', '{"2025":175,"unite":48,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 17, 'CARTON LAIT MY FAMILY CARE 125ML', 'ALMOND', '{"2025":660,"unite":72,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":1000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 18, 'CARTON LAIT MY FAMILY CARE 250ML', 'ALMOND', '{"2025":1850,"unite":48,"avis":null,"statistique 4D 6 mois":6000,"STAT ALMOND":2000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 19, 'CARTON LAIT MY FAMILY CARE 500ML', 'ALMOND', '{"2025":3000,"unite":24,"avis":0,"statistique 4D 6 mois":10000,"STAT ALMOND":3500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 20, 'CARTON LAIT MY FAMILY CARE 750ML', 'ALMOND', '{"2025":1500,"unite":12,"avis":0,"statistique 4D 6 mois":5000,"STAT ALMOND":2000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 21, 'CARTON SAVON MY FAMILY CARE 190GR', 'ALMOND', '{"2025":300,"unite":48,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 22, 'CARTON TALC MY FAMILY CARE 100GR', 'ALMOND', '{"2025":220,"unite":96,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 23, 'CARTON TALC MY FAMILY CARE 200GR', 'ALMOND', '{"2025":450,"unite":72,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 24, 'CARTON TALC MY FAMILY CARE 400GR', 'ALMOND', '{"2025":650,"unite":48,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":1000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 25, 'CARTON TALC MY FAMILY CARE 50GR', 'ALMOND', '{"2025":550,"unite":120,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":1000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 26, 'CARTON TALC MY FAMILY CARE 600GR', 'ALMOND', '{"2025":500,"unite":24,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":1000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 27, 'CARTON KIT MY FAMILY CARE', 'ALMOND', '{"2025":0,"unite":"6pcs","avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 28, 'CARTON VASELINE MY FAMILY CARE 100ML', 'ALMOND', '{"2025":800,"unite":72,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":1000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 29, 'CARTON VASELINE MY FAMILY CARE 200ML', 'ALMOND', '{"2025":1000,"unite":36,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":1000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 30, 'CARTON VASELINE MY FAMILY CARE 400ML', 'ALMOND', '{"2025":800,"unite":24,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":1000,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 31, 'CARTON VASELINE MY FAMILY CARE 900ML', 'ALMOND', '{"2025":1100,"unite":12,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":1500,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 32, 'ETIQUETTE EAU COLOGNE FAMILY CARE ALMOND&DOLPHIN 250ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 33, 'ETIQUETTE EAU COLOGNE FAMILY CARE ALMOND&DOLPHIN 500ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 34, 'ETIQUETTE EAU COLOGNE FAMILY CARE ALMOND&DOLPHIN 750ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":6000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 35, 'ETIQUETTE GEL DOUCHE FAMILY CARE ALMOND&DOLPHIN 125ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 36, 'ETIQUETTE GEL DOUCHE FAMILY CARE ALMOND&DOLPHIN 250ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 37, 'ETIQUETTE GEL DOUCHE FAMILY CARE ALMOND&DOLPHIN 500ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 38, 'ETIQUETTE GEL DOUCHE FAMILY CARE ALMOND&DOLPHIN 750ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 39, 'ETUIS SAVON FAMILY CARE ALMOND&DOLPHIN 190GR', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 40, 'GIFT BOX FAMILY CARE  (BODY)', 'ALMOND', '{"2025":2000,"unite":null,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 41, 'GIFT BOX FAMILY CARE (INSERT)', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 42, 'GIFT BAG TRANSP.PVC MY FAMILY CARE', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 43, 'GIFT BOX FAMILY CARE ALMOND&DOLPHIN (COVER BLUE)', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":750,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 44, 'PAPER GB MY FAMILY CARE ALMOND&DOLPHIN', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 45, 'SLEEVE CREME FAMILY CARE ALMOND&DOLPHIN 100ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 46, 'SLEEVE CREME FAMILY CARE ALMOND&DOLPHIN 200ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 47, 'SLEEVE CREME FAMILY CARE ALMOND&DOLPHIN 400ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 48, 'SLEEVE CREME FAMILY CARE ALMOND&DOLPHIN 900ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 49, 'SLEEVE HUILE FAMILY CARE ALMOND&DOLPHIN 90ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 50, 'SLEEVE LAIT FAMILY CARE ALMOND&DOLPHIN 125ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":72000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 51, 'SLEEVE LAIT FAMILY CARE ALMOND&DOLPHIN 250ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":96000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 52, 'SLEEVE LAIT FAMILY CARE ALMOND&DOLPHIN 500ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":84000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 53, 'SLEEVE LAIT FAMILY CARE ALMOND&DOLPHIN 750ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 54, 'SLEEVE TALC FAMILY CARE ALMOND&DOLPHIN 100GR', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":48000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 55, 'SLEEVE TALC FAMILY CARE ALMOND&DOLPHIN 200GR', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 56, 'SLEEVE TALC FAMILY CARE ALMOND&DOLPHIN 400GR', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":48000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 57, 'SLEEVE TALC FAMILY CARE ALMOND&DOLPHIN 50GR', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":120000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 58, 'SLEEVE TALC FAMILY CARE ALMOND&DOLPHIN 600GR', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 59, 'SLEEVE VASELINE FAMILY CARE ALMOND&DOLPHIN 100ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":72000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 60, 'SLEEVE VASELINE FAMILY CARE ALMOND&DOLPHIN 200ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 61, 'SLEEVE VASELINE FAMILY CARE ALMOND&DOLPHIN 400ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 62, 'SLEEVE VASELINE FAMILY CARE ALMOND&DOLPHIN 900ML', 'ALMOND', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":18000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 63, 'BASE MEDITERANEAN ALOE1036498', 'ALOE VERA', '{"2025":535,"unite":"IBR","avis":null,"statistique 4D 6 mois":400,"STAT ALMOND":null,"remarque":"AUTRES"}'::jsonb),
  ('MY FAMILY CARE', 64, 'BASE ALM 11418', 'ALOE VERA', '{"2025":225,"unite":"NP","avis":null,"statistique 4D 6 mois":200,"STAT ALMOND":null,"remarque":"EDC+ TALC"}'::jsonb),
  ('MY FAMILY CARE', 65, 'CARTON CREME MY FAMILY CARE 100ML', 'ALOE VERA', '{"2025":185,"unite":72,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 66, 'CARTON CREME MY FAMILY CARE 200ML', 'ALOE VERA', '{"2025":295,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 67, 'CARTON CREME MY FAMILY CARE 400ML', 'ALOE VERA', '{"2025":360,"unite":24,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 68, 'CARTON CREME MY FAMILY CARE 900ML', 'ALOE VERA', '{"2025":295,"unite":12,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 69, 'CARTON EDC MY FAMILY CARE 250ML', 'ALOE VERA', '{"2025":215,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 70, 'CARTON EDC MY FAMILY CARE 500ML', 'ALOE VERA', '{"2025":190,"unite":24,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 71, 'CARTON EDC MY FAMILY CARE 750ML', 'ALOE VERA', '{"2025":180,"unite":12,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 72, 'CARTON GEL DOUCHE MY FAMILY CARE 125ML', 'ALOE VERA', '{"2025":null,"unite":72,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 73, 'CARTON GEL DOUCHE MY FAMILY CARE 250ML', 'ALOE VERA', '{"2025":null,"unite":48,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 74, 'CARTON GEL DOUCHE MY FAMILY CARE 500ML', 'ALOE VERA', '{"2025":null,"unite":24,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 75, 'CARTON GEL DOUCHE MY FAMILY CARE 750ML', 'ALOE VERA', '{"2025":1810,"unite":12,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 76, 'CARTON GIFT BOX MY FAMILY CARE', 'ALOE VERA', '{"2025":450,"unite":6,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":"Voir ALMOND"}'::jsonb),
  ('MY FAMILY CARE', 77, 'CARTON HUILE MY FAMILY CARE 90ML', 'ALOE VERA', '{"2025":180,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 78, 'CARTON LAIT MY FAMILY CARE 125ML', 'ALOE VERA', '{"2025":410,"unite":72,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 79, 'CARTON LAIT MY FAMILY CARE 250ML', 'ALOE VERA', '{"2025":1475,"unite":48,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 80, 'CARTON LAIT MY FAMILY CARE 500ML', 'ALOE VERA', '{"2025":2450,"unite":24,"avis":null,"statistique 4D 6 mois":2500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 81, 'CARTON LAIT MY FAMILY CARE 750ML', 'ALOE VERA', '{"2025":1280,"unite":12,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 82, 'CARTON SAVON MY FAMILY CARE 190GR', 'ALOE VERA', '{"2025":280,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 83, 'CARTON TALC MY FAMILY CARE 100GR', 'ALOE VERA', '{"2025":205,"unite":96,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 84, 'CARTON TALC MY FAMILY CARE 200GR', 'ALOE VERA', '{"2025":400,"unite":72,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 85, 'CARTON TALC MY FAMILY CARE 400GR', 'ALOE VERA', '{"2025":575,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 86, 'CARTON TALC MY FAMILY CARE 50GR', 'ALOE VERA', '{"2025":450,"unite":120,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 87, 'CARTON TALC MY FAMILY CARE 600GR', 'ALOE VERA', '{"2025":475,"unite":24,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 88, 'CARTON KIT MY FAMILY CARE', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 89, 'CARTON VASELINE MY FAMILY CARE 100ML', 'ALOE VERA', '{"2025":720,"unite":60,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 90, 'CARTON VASELINE MY FAMILY CARE 200ML', 'ALOE VERA', '{"2025":865,"unite":36,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 91, 'CARTON VASELINE MY FAMILY CARE 400ML', 'ALOE VERA', '{"2025":800,"unite":24,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 92, 'CARTON VASELINE MY FAMILY CARE 900ML', 'ALOE VERA', '{"2025":840,"unite":12,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 93, 'ETIQUETTE EAU COLOGNE FAMILY CARE ALOE.V&PEACOCK 250ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 94, 'ETIQUETTE EAU COLOGNE FAMILY CARE ALOE.V&PEACOCK 500ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 95, 'ETIQUETTE EAU COLOGNE FAMILY CARE ALOE.V&PEACOCK 750ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":6000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 96, 'ETIQUETTE GEL DOUCHE FAMILY CARE ALOE.V&PEACOCK 125ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 97, 'ETIQUETTE GEL DOUCHE FAMILY CARE ALOE.V&PEACOCK 250ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 98, 'ETIQUETTE GEL DOUCHE FAMILY CARE ALOE.V&PEACOCK 500ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 99, 'ETIQUETTE GEL DOUCHE FAMILY CARE ALOE.V&PEACOCK 750ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 100, 'ETUIS SAVON FAMILY CARE ALOE.V&PEACOCK 190GR', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 101, 'GIFT BOX FAMILY CARE ALOE VERA&PEACOCK (BODY)', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":0,"STAT ALMOND":null,"remarque":"Voir ALMOND","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 102, 'GIFT BOX FAMILY CARE ALOE VERA&PEACOCK (INSERT)', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":0,"STAT ALMOND":null,"remarque":"Voir ALMOND","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 103, 'GIFT BAG TRANSP.PVC MY FAMILY CARE', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":0,"STAT ALMOND":null,"remarque":"Voir ALMOND","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 104, 'GIFT BOX FAMILY CARE ALOE VERA&PEACOCK (COVER GREEN)', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":750,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 105, 'PAPER GB MY FAMILY CARE ALOEVERA&PEACOCK', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 106, 'SLEEVE CREME FAMILY CARE ALOE.V&PEACOCK 100ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 107, 'SLEEVE CREME FAMILY CARE ALOE.V&PEACOCK 200ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 108, 'SLEEVE CREME FAMILY CARE ALOE.V&PEACOCK 400ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 109, 'SLEEVE CREME FAMILY CARE ALOE.V&PEACOCK 900ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":6000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 110, 'SLEEVE HUILE FAMILY CARE ALOE.V&PEACOCK 90ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 111, 'SLEEVE LAIT FAMILY CARE ALOE.V&PEACOCK 125ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":72000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 112, 'SLEEVE LAIT FAMILY CARE ALOE.V&PEACOCK 250ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":72000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 113, 'SLEEVE LAIT FAMILY CARE ALOE.V&PEACOCK 500ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":60000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 114, 'SLEEVE LAIT FAMILY CARE ALOE.V&PEACOCK 750ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":18000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 115, 'SLEEVE TALC FAMILY CARE ALOE.V&PEACOCK 100GR', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":48000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 116, 'SLEEVE TALC FAMILY CARE ALOE.V&PEACOCK 200GR', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 117, 'SLEEVE TALC FAMILY CARE ALOE.V&PEACOCK 400GR', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 118, 'SLEEVE TALC FAMILY CARE ALOE.V&PEACOCK 50GR', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":60000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 119, 'SLEEVE TALC FAMILY CARE ALOE.V&PEACOCK 600GR', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 120, 'SLEEVE VASELINE FAMILY CARE ALOE.V&PEACOCK 100ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":60000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 121, 'SLEEVE VASELINE FAMILY CARE ALOE.V&PEACOCK 200ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 122, 'SLEEVE VASELINE FAMILY CARE ALOE.V&PEACOCK 400ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 123, 'SLEEVE VASELINE FAMILY CARE ALOE.V&PEACOCK 900ML', 'ALOE VERA', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 124, 'BASE SAV 40059', 'POMEGRANATE', '{"2025":520,"unite":"NP","avis":null,"statistique 4D 6 mois":400,"STAT ALMOND":null,"remarque":"AUTRES"}'::jsonb),
  ('MY FAMILY CARE', 125, 'BASE ALD 21217', 'POMEGRANATE', '{"2025":225,"unite":"NP","avis":null,"statistique 4D 6 mois":200,"STAT ALMOND":null,"remarque":"EDC+TALC"}'::jsonb),
  ('MY FAMILY CARE', 126, 'CARTON CREME MY FAMILY CARE 100ML', 'POMEGRANATE', '{"2025":160,"unite":72,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 127, 'CARTON CREME MY FAMILY CARE 200ML', 'POMEGRANATE', '{"2025":270,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 128, 'CARTON CREME MY FAMILY CARE 400ML', 'POMEGRANATE', '{"2025":500,"unite":24,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 129, 'CARTON CREME MY FAMILY CARE 900ML', 'POMEGRANATE', '{"2025":350,"unite":12,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 130, 'CARTON EDC MY FAMILY CARE 250ML', 'POMEGRANATE', '{"2025":200,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 131, 'CARTON EDC MY FAMILY CARE 500ML', 'POMEGRANATE', '{"2025":180,"unite":24,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 132, 'CARTON EDC MY FAMILY CARE 750ML', 'POMEGRANATE', '{"2025":160,"unite":12,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":"Voir ALMOND"}'::jsonb),
  ('MY FAMILY CARE', 133, 'CARTON GEL DOUCHE MY FAMILY CARE 125ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 134, 'CARTON GEL DOUCHE MY FAMILY CARE 250ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 135, 'CARTON GEL DOUCHE MY FAMILY CARE 500ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 136, 'CARTON GEL DOUCHE MY FAMILY CARE 750ML', 'POMEGRANATE', '{"2025":1950,"unite":12,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 137, 'CARTON GIFT BOX MY FAMILY CARE', 'POMEGRANATE', '{"2025":390,"unite":6,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 138, 'CARTON HUILE MY FAMILY CARE 90ML', 'POMEGRANATE', '{"2025":170,"unite":48,"avis":null,"statistique 4D 6 mois":200,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 139, 'CARTON LAIT MY FAMILY CARE 125ML', 'POMEGRANATE', '{"2025":525,"unite":72,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 140, 'CARTON LAIT MY FAMILY CARE 250ML', 'POMEGRANATE', '{"2025":1450,"unite":48,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 141, 'CARTON LAIT MY FAMILY CARE 500ML', 'POMEGRANATE', '{"2025":2120,"unite":24,"avis":null,"statistique 4D 6 mois":2500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 142, 'CARTON LAIT MY FAMILY CARE 750ML', 'POMEGRANATE', '{"2025":1115,"unite":12,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 143, 'CARTON SAVON MY FAMILY CARE 190GR', 'POMEGRANATE', '{"2025":225,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 144, 'CARTON TALC MY FAMILY CARE 100GR', 'POMEGRANATE', '{"2025":175,"unite":96,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 145, 'CARTON TALC MY FAMILY CARE 200GR', 'POMEGRANATE', '{"2025":415,"unite":72,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 146, 'CARTON TALC MY FAMILY CARE 400GR', 'POMEGRANATE', '{"2025":530,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 147, 'CARTON TALC MY FAMILY CARE 50GR', 'POMEGRANATE', '{"2025":470,"unite":120,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 148, 'CARTON TALC MY FAMILY CARE 600GR', 'POMEGRANATE', '{"2025":460,"unite":24,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 149, 'CARTON KIT MY FAMILY CARE', 'POMEGRANATE', '{"2025":null,"unite":6,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 150, 'CARTON VASELINE MY FAMILY CARE 100ML', 'POMEGRANATE', '{"2025":725,"unite":60,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 151, 'CARTON VASELINE MY FAMILY CARE 200ML', 'POMEGRANATE', '{"2025":850,"unite":36,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 152, 'CARTON VASELINE MY FAMILY CARE 400ML', 'POMEGRANATE', '{"2025":680,"unite":24,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 153, 'CARTON VASELINE MY FAMILY CARE 900ML', 'POMEGRANATE', '{"2025":760,"unite":12,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 154, 'ETIQUETTE EAU COLOGNE FAMILY CARE POMEGRANATE&BF.250ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 155, 'ETIQUETTE EAU COLOGNE FAMILY CARE POMEGRANATE&BF.500ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 156, 'ETIQUETTE EAU COLOGNE FAMILY CARE POMEGRANATE&BF.750ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":6000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 157, 'ETIQUETTE GEL DOUCHE FAMILY CARE POMEGRANATE&BF.125ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 158, 'ETIQUETTE GEL DOUCHE FAMILY CARE POMEGRANATE&BF.250ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 159, 'ETIQUETTE GEL DOUCHE FAMILY CARE POMEGRANATE&BF.500ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 160, 'ETIQUETTE GEL DOUCHE FAMILY CARE POMEGRANATE&BF.750ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 161, 'ETUIS SAVON FAMILY CARE POMEGRANATE&BF.190GR', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 162, 'GIFT BOX FAMILY CARE POMEGRANATE&BUTTERFLY (BODY)', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":9000,"STAT ALMOND":null,"remarque":"Voir ALMOND","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 163, 'GIFT BOX FAMILY CARE POMEGRANATE&BUTTERFLY (INSERT)', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":9000,"STAT ALMOND":null,"remarque":"Voir ALMOND","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 164, 'GIFT BAG TRANSP.PVC MY FAMILY CARE', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":"Voir ALMOND","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 165, 'GIFT BOX FAMILY CARE POMEGRANATE&BUTTERFLY (COVER PINK)', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":750,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 166, 'PAPER GB MY FAMILY CARE POMEGRANATE&BF', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 167, 'SLEEVE CREME FAMILY CARE POMEGRANATE&BF.100ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 168, 'SLEEVE CREME FAMILY CARE POMEGRANATE&BF.200ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 169, 'SLEEVE CREME FAMILY CARE POMEGRANATE&BF.400ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 170, 'SLEEVE CREME FAMILY CARE POMEGRANATE&BF.900ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":6000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 171, 'SLEEVE HUILE FAMILY CARE POMEGRANATE&BF.90ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 172, 'SLEEVE LAIT FAMILY CARE POMEGRANATE&BF.125ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 173, 'SLEEVE LAIT FAMILY CARE POMEGRANATE&BF.250ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":72000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 174, 'SLEEVE LAIT FAMILY CARE POMEGRANATE&BF.500ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":60000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"FFFF00"}'::jsonb),
  ('MY FAMILY CARE', 175, 'SLEEVE LAIT FAMILY CARE POMEGRANATE&BF.750ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":18000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 176, 'SLEEVE TALC FAMILY CARE POMEGRANATE&BF.100GR', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":48000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 177, 'SLEEVE TALC FAMILY CARE POMEGRANATE&BF.200GR', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 178, 'SLEEVE TALC FAMILY CARE POMEGRANATE&BF.400GR', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 179, 'SLEEVE TALC FAMILY CARE POMEGRANATE&BF.50GR', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":60000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 180, 'SLEEVE TALC FAMILY CARE POMEGRANATE&BF.600GR', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 181, 'SLEEVE VASELINE FAMILY CARE POMEGRANATE&BF.100ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":60000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 182, 'SLEEVE VASELINE FAMILY CARE POMEGRANATE&BF.200ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 183, 'SLEEVE VASELINE FAMILY CARE POMEGRANATE&BF.400ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 184, 'SLEEVE VASELINE FAMILY CARE POMEGRANATE&BF.900ML', 'POMEGRANATE', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 185, 'BASE SAV 40217', 'LEMON', '{"2025":460,"unite":"NP","avis":0,"statistique 4D 6 mois":400,"STAT ALMOND":null,"remarque":"LAIT /PDE"}'::jsonb),
  ('MY FAMILY CARE', 186, 'BASE LEMON LIME 1974314', 'LEMON', '{"2025":90,"unite":"IBR","avis":null,"statistique 4D 6 mois":75,"STAT ALMOND":null,"remarque":"SAV+ GEL D "}'::jsonb),
  ('MY FAMILY CARE', 187, 'BASE CLG 50122', 'LEMON', '{"2025":190,"unite":"NP","avis":null,"statistique 4D 6 mois":150,"STAT ALMOND":null,"remarque":"EDC+TALC"}'::jsonb),
  ('MY FAMILY CARE', 188, 'CARTON CREME MY FAMILY CARE 100ML', 'LEMON', '{"2025":150,"unite":72,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 189, 'CARTON CREME MY FAMILY CARE 200ML', 'LEMON', '{"2025":260,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 190, 'CARTON CREME MY FAMILY CARE 400ML', 'LEMON', '{"2025":190,"unite":24,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 191, 'CARTON CREME MY FAMILY CARE 900ML', 'LEMON', '{"2025":405,"unite":12,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 192, 'CARTON EDC MY FAMILY CARE 250ML', 'LEMON', '{"2025":205,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 193, 'CARTON EDC MY FAMILY CARE 500ML', 'LEMON', '{"2025":180,"unite":24,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 194, 'CARTON EDC MY FAMILY CARE 750ML', 'LEMON', '{"2025":160,"unite":12,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 195, 'CARTON GEL DOUCHE MY FAMILY CARE 125ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 196, 'CARTON GEL DOUCHE MY FAMILY CARE 250ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 197, 'CARTON GEL DOUCHE MY FAMILY CARE 500ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 198, 'CARTON GEL DOUCHE MY FAMILY CARE 750ML', 'LEMON', '{"2025":1850,"unite":12,"avis":null,"statistique 4D 6 mois":2000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 199, 'CARTON GIFT BOX MY FAMILY CARE', 'LEMON', '{"2025":430,"unite":6,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 200, 'CARTON HUILE MY FAMILY CARE 90ML', 'LEMON', '{"2025":165,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 201, 'CARTON LAIT MY FAMILY CARE 125ML', 'LEMON', '{"2025":410,"unite":72,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 202, 'CARTON LAIT MY FAMILY CARE 250ML', 'LEMON', '{"2025":1160,"unite":48,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 203, 'CARTON LAIT MY FAMILY CARE 500ML', 'LEMON', '{"2025":2210,"unite":24,"avis":null,"statistique 4D 6 mois":2500,"STAT ALMOND":null,"remarque":"Voir ALMOND"}'::jsonb),
  ('MY FAMILY CARE', 204, 'CARTON LAIT MY FAMILY CARE 750ML', 'LEMON', '{"2025":1060,"unite":12,"avis":null,"statistique 4D 6 mois":1500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 205, 'CARTON SAVON MY FAMILY CARE 190GR', 'LEMON', '{"2025":270,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 206, 'CARTON TALC MY FAMILY CARE 100GR', 'LEMON', '{"2025":190,"unite":96,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 207, 'CARTON TALC MY FAMILY CARE 200GR', 'LEMON', '{"2025":420,"unite":72,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 208, 'CARTON TALC MY FAMILY CARE 400GR', 'LEMON', '{"2025":555,"unite":48,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 209, 'CARTON TALC MY FAMILY CARE 50GR', 'LEMON', '{"2025":480,"unite":120,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 210, 'CARTON TALC MY FAMILY CARE 600GR', 'LEMON', '{"2025":480,"unite":24,"avis":null,"statistique 4D 6 mois":500,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 211, 'CARTON KIT MY FAMILY CARE', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 212, 'CARTON VASELINE MY FAMILY CARE 100ML', 'LEMON', '{"2025":750,"unite":60,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 213, 'CARTON VASELINE MY FAMILY CARE 200ML', 'LEMON', '{"2025":850,"unite":36,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 214, 'CARTON VASELINE MY FAMILY CARE 400ML', 'LEMON', '{"2025":780,"unite":24,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 215, 'CARTON VASELINE MY FAMILY CARE 900ML', 'LEMON', '{"2025":1050,"unite":12,"avis":null,"statistique 4D 6 mois":1000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 216, 'ETIQUETTE EAU COLOGNE FAMILY CARE CITRON&CANARI 250ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 217, 'ETIQUETTE EAU COLOGNE FAMILY CARE CITRON&CANARI 500ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 218, 'ETIQUETTE EAU COLOGNE FAMILY CARE CITRON&CANARI 750ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":6000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 219, 'ETIQUETTE GEL DOUCHE FAMILY CARE CITRON&CANARI 125ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 220, 'ETIQUETTE GEL DOUCHE FAMILY CARE CITRON&CANARI 250ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 221, 'ETIQUETTE GEL DOUCHE FAMILY CARE CITRON&CANARI 500ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 222, 'ETIQUETTE GEL DOUCHE FAMILY CARE CITRON&CANARI 750ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 223, 'ETUIS SAVON FAMILY CARE CITRON&CANARI 190GR', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 224, 'GIFT BOX FAMILY CARE LEMON&CANARI (BODY)', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":9000,"STAT ALMOND":null,"remarque":"Voir ALMOND","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 225, 'GIFT BOX FAMILY CARE LEMON&CANARI (INSERT)', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":9000,"STAT ALMOND":null,"remarque":"Voir ALMOND","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 226, 'GIFT BAG TRANSP.PVC MY FAMILY CARE', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":null,"STAT ALMOND":null,"remarque":"Voir ALMOND","designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 227, 'GIFT BOX FAMILY CARE LEMON&CANARI (COVER YELLOW)', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":750,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 228, 'PAPER GB MY FAMILY CARE CITRON&CANARI', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":3000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"EBF1DE"}'::jsonb),
  ('MY FAMILY CARE', 229, 'SLEEVE CREME FAMILY CARE CITRON&CANARI 100ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 230, 'SLEEVE CREME FAMILY CARE CITRON&CANARI 200ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 231, 'SLEEVE CREME FAMILY CARE CITRON&CANARI 400ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 232, 'SLEEVE CREME FAMILY CARE CITRON&CANARI 900ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":6000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 233, 'SLEEVE HUILE FAMILY CARE CITRON&CANARI 90ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 234, 'SLEEVE LAIT FAMILY CARE CITRON&CANARI 125ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 235, 'SLEEVE LAIT FAMILY CARE CITRON&CANARI 250ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":72000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 236, 'SLEEVE LAIT FAMILY CARE CITRON&CANARI 500ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":60000,"STAT ALMOND":null,"remarque":null,"designation_couleur":"FFFF00"}'::jsonb),
  ('MY FAMILY CARE', 237, 'SLEEVE LAIT FAMILY CARE CITRON&CANARI 750ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":18000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 238, 'SLEEVE TALC FAMILY CARE CITRON&CANARI 100GR', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":48000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 239, 'SLEEVE TALC FAMILY CARE CITRON&CANARI 200GR', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 240, 'SLEEVE TALC FAMILY CARE CITRON&CANARI 400GR', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 241, 'SLEEVE TALC FAMILY CARE CITRON&CANARI 50GR', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":60000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 242, 'SLEEVE TALC FAMILY CARE CITRON&CANARI 600GR', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 243, 'SLEEVE VASELINE FAMILY CARE CITRON&CANARI 100ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":60000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 244, 'SLEEVE VASELINE FAMILY CARE CITRON&CANARI 200ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":36000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 245, 'SLEEVE VASELINE FAMILY CARE CITRON&CANARI 400ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":24000,"STAT ALMOND":null,"remarque":null}'::jsonb),
  ('MY FAMILY CARE', 246, 'SLEEVE VASELINE FAMILY CARE CITRON&CANARI 900ML', 'LEMON', '{"2025":null,"unite":null,"avis":null,"statistique 4D 6 mois":12000,"STAT ALMOND":null,"remarque":null}'::jsonb)
on conflict (gamme_statistique, ordre) do update set
  designation = excluded.designation,
  categorie = excluded.categorie,
  donnees = excluded.donnees;
