-- Import du rapport PARFUM (onboarding multi-gammes Statistique MP).
-- 51 articles. Fichier source multi-onglets : ordre renumerote sequentiellement (1..51), la sous-famille d'origine est gardee dans la colonne categorie.
-- A executer dans Supabase SQL Editor (la table existe deja, creee pour MP COSM).

insert into public.rapport_gamme_statistique_mp
  (gamme_statistique, ordre, designation, categorie, donnees)
values
  ('PARFUM', 1, 'BASE COS 30239 POMMADE CDV ROSE', 'PINK FLOWER', '{"unite":"NP","avis":null,"statistique 4D 6mois":null,"remarque":"CONSO 125KG / ANS"}'::jsonb),
  ('PARFUM', 2, 'ETUIS PARFUM PINK FLOWER 90ML', 'PINK FLOWER', '{"unite":null,"avis":null,"statistique 4D 6mois":36000,"remarque":null}'::jsonb),
  ('PARFUM', 3, 'GLASS BOTTLES PINK FLOWER 90 ML', 'PINK FLOWER', '{"unite":null,"avis":null,"statistique 4D 6mois":36000,"remarque":null}'::jsonb),
  ('PARFUM', 4, 'PLASTIC PUMP 18 MM P232C PINK', 'PINK FLOWER', '{"unite":null,"avis":null,"statistique 4D 6mois":36000,"remarque":null}'::jsonb),
  ('PARFUM', 5, 'CARTON PARFUM LEGACY', 'PINK FLOWER', '{"unite":null,"avis":null,"statistique 4D 6mois":null,"remarque":450}'::jsonb),
  ('PARFUM', 6, 'BASE SABAYA 6RL 54244 / ALD 24981', 'PURE SENSATION', '{"unite":"CARB","avis":25,"statistique 4D 6mois":60,"remarque":0}'::jsonb),
  ('PARFUM', 7, 'ETUIS PARFUM PURE SENSATION 90ML', 'PURE SENSATION', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 8, 'GLASS BOTTLES PURE SENSATION 90ML', 'PURE SENSATION', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 9, 'PLASTIC PUMP 18MM P 3252 C GREEN', 'PURE SENSATION', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 10, 'CARTON PARFUM LEGACY', 'PURE SENSATION', '{"unite":null,"avis":null,"statistique 4D 6mois":"-","remarque":52}'::jsonb),
  ('PARFUM', 11, 'CARTON PARFUM LEGACY', 'LEGACY CLASS', '{"unite":"6dz","avis":null,"statistique 4D 6mois":null,"remarque":185}'::jsonb),
  ('PARFUM', 12, 'BASE ALD 21147', 'LEGACY CLASS', '{"unite":"NP","avis":25,"statistique 4D 6mois":75,"remarque":"60 KG / ANS"}'::jsonb),
  ('PARFUM', 13, 'ETUIS PARFUM LEGACY CLASSIC 90ML', 'LEGACY CLASS', '{"unite":null,"avis":0,"statistique 4D 6mois":21600,"remarque":null}'::jsonb),
  ('PARFUM', 14, 'GLASS BOTTLES LEGACY CLASSIC 90ML', 'LEGACY CLASS', '{"unite":null,"avis":0,"statistique 4D 6mois":21600,"remarque":null}'::jsonb),
  ('PARFUM', 15, 'PLASTIC PUMP 18MM YELLOW', 'LEGACY CLASS', '{"unite":null,"avis":null,"statistique 4D 6mois":21600,"remarque":null}'::jsonb),
  ('PARFUM', 16, 'CARTON PARFUM LEGACY', 'LEGACY AUT', '{"unite":null,"avis":null,"statistique 4D 6mois":null,"remarque":145}'::jsonb),
  ('PARFUM', 17, 'BASE SHAIKHAH 32572', 'LEGACY AUT', '{"unite":"CARB","avis":25,"statistique 4D 6mois":30,"remarque":0}'::jsonb),
  ('PARFUM', 18, 'ETUIS PARFUM LEGACY AUTHENTIC 90ML', 'LEGACY AUT', '{"unite":null,"avis":null,"statistique 4D 6mois":11000,"remarque":null}'::jsonb),
  ('PARFUM', 19, 'GLASS BOTTLES LEGACY AUTHENTIC 90ML', 'LEGACY AUT', '{"unite":null,"avis":null,"statistique 4D 6mois":11000,"remarque":null}'::jsonb),
  ('PARFUM', 20, 'PLASTIC PUMP 18MM BLACK', 'LEGACY AUT', '{"unite":null,"avis":null,"statistique 4D 6mois":null,"remarque":null}'::jsonb),
  ('PARFUM', 21, 'BASE VANETY - 1172610-VANITY CP23002', 'ELIXIR SPECIAL', '{"unite":"ME","avis":null,"statistique 4D 6mois":100,"remarque":"620 KG /ANS"}'::jsonb),
  ('PARFUM', 22, 'ETUIS PARFUM ELIXIR SPECIAL 90ML', 'ELIXIR SPECIAL', '{"unite":null,"avis":null,"statistique 4D 6mois":25200,"remarque":null}'::jsonb),
  ('PARFUM', 23, 'GLASS BOTTLES ELIXIR 90 ML', 'ELIXIR SPECIAL', '{"unite":null,"avis":null,"statistique 4D 6mois":25200,"remarque":null}'::jsonb),
  ('PARFUM', 24, 'PLASTIC PUMP 18MM P2695C PURPLE', 'ELIXIR SPECIAL', '{"unite":null,"avis":null,"statistique 4D 6mois":25200,"remarque":null}'::jsonb),
  ('PARFUM', 25, 'CARTON PARFUM LEGACY', 'ELIXIR SPECIAL', '{"unite":null,"avis":null,"statistique 4D 6mois":350,"remarque":370}'::jsonb),
  ('PARFUM', 26, 'BASE BELLISSIMA AR375222', 'EXELLENCE WOMEN', '{"unite":"CPL","avis":null,"statistique 4D 6mois":98,"remarque":0}'::jsonb),
  ('PARFUM', 27, 'SLEEVES EXELLENCE WOMAN', 'EXELLENCE WOMEN', '{"unite":null,"avis":null,"statistique 4D 6mois":8400,"remarque":null}'::jsonb),
  ('PARFUM', 28, 'PET 250 ML BOTTLE UNIQUE BS-063', 'EXELLENCE WOMEN', '{"unite":null,"avis":null,"statistique 4D 6mois":8400,"remarque":null}'::jsonb),
  ('PARFUM', 29, 'SPRAYER POMPE UNIQUE BLANC 24/410', 'EXELLENCE WOMEN', '{"unite":null,"avis":null,"statistique 4D 6mois":8400,"remarque":null}'::jsonb),
  ('PARFUM', 30, 'CARTONS EXELLENCE WOMAN', 'EXELLENCE WOMEN', '{"unite":"2dz","avis":null,"statistique 4D 6mois":350,"remarque":null}'::jsonb),
  ('PARFUM', 31, 'BASE SABAYA 6RL 54244 / ALD 24981', 'SCANDAL FEMME', '{"unite":"CARB","avis":null,"statistique 4D 6mois":null,"remarque":null}'::jsonb),
  ('PARFUM', 32, 'CAL SCANDAL FEMME 100ML WHITE LINER', 'SCANDAL FEMME', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 33, 'ETUIS SCANDAL 100ML FEMME', 'SCANDAL FEMME', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 34, 'CARTON EDT SCANDAL FEMME', 'SCANDAL FEMME', '{"unite":"3dz","avis":null,"statistique 4D 6mois":500,"remarque":null}'::jsonb),
  ('PARFUM', 35, 'GLASS BOTTLE ( FLACON EN VERRE ) SCANDAL FEMME 4941H', 'SCANDAL FEMME', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 36, 'RING(BAGUE) SCANDAL FEMME 4941H', 'SCANDAL FEMME', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 37, 'PLASTIC CAP ( BOUCHON ) SCANDAL FEMME 4941H', 'SCANDAL FEMME', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 38, 'PUMP ( POMPE ) SCANDAL FEMME', 'SCANDAL FEMME', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 39, 'BASE EXPLORE 55226', 'GLADIATOR', '{"unite":"CARB","avis":0,"statistique 4D 6mois":50,"remarque":null}'::jsonb),
  ('PARFUM', 40, 'CARTON EDT GLADIATOR', 'GLADIATOR', '{"unite":"3dz","avis":null,"statistique 4D 6mois":350,"remarque":null}'::jsonb),
  ('PARFUM', 41, 'ETUIS GLADIATOR 100ML HOMME', 'GLADIATOR', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 42, 'CAL GLADIATOR 100ML BLACK LINER HOMME', 'GLADIATOR', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 43, 'GLASS BOTTLE A 1542  ( FLACON GLADIATOR)', 'GLADIATOR', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 44, 'RING (BAGUE) GLADIATOR', 'GLADIATOR', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 45, 'PUMP ( POMPE ) GLADIATOR', 'GLADIATOR', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 46, 'CAPSULES PLASTIQUE GLADIATOR', 'GLADIATOR', '{"unite":null,"avis":null,"statistique 4D 6mois":18000,"remarque":null}'::jsonb),
  ('PARFUM', 47, 'BASE BRUTISIO ( BOLIVAR 550407 )', 'TARGET', '{"unite":"LUZI","avis":null,"statistique 4D 6mois":3000,"remarque":"4,6 T / ANS"}'::jsonb),
  ('PARFUM', 48, 'ETUIS PARFUM TARGETS 90ML', 'TARGET', '{"unite":null,"avis":null,"statistique 4D 6mois":576000,"remarque":null}'::jsonb),
  ('PARFUM', 49, 'PLASTIC PUMP 18MM BLACK', 'TARGET', '{"unite":null,"avis":null,"statistique 4D 6mois":576000,"remarque":null}'::jsonb),
  ('PARFUM', 50, 'GLASS BOTTLES TARGET 90ML', 'TARGET', '{"unite":null,"avis":null,"statistique 4D 6mois":576000,"remarque":null}'::jsonb),
  ('PARFUM', 51, 'CARTON PARFUM LEGACY', 'TARGET', '{"unite":"6DZ","avis":2000,"statistique 4D 6mois":8000,"remarque":10100}'::jsonb)
on conflict (gamme_statistique, ordre) do update set
  designation = excluded.designation,
  categorie = excluded.categorie,
  donnees = excluded.donnees;
